import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import "./IrisIntelligenceScreens.css";

type Capability = { id: string; name: string; description: string; family: string; depth: string };

export function IrisCatalog({ go }: { go?: (page: string) => void }) {
  const [catalog, setCatalog] = useState<Capability[]>([]), [selected, setSelected] = useState<string[]>([]), [family, setFamily] = useState("all"), [query, setQuery] = useState(""), [saving, setSaving] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { api.getIrisCatalog().then(data => { setCatalog(data.catalog ?? []); setSelected(data.selection?.capability_ids ?? []); }).catch(e => setMessage(e instanceof Error ? e.message : "Unable to load catalog.")); }, []);
  const families = useMemo(() => [...new Set(catalog.map(c => c.family))].sort(), [catalog]);
  const visible = useMemo(() => catalog.filter(c => (family === "all" || c.family === family) && (!query.trim() || `${c.name} ${c.description} ${c.family}`.toLowerCase().includes(query.toLowerCase()))), [catalog, family, query]);
  const active = useMemo(() => catalog.filter(c => selected.includes(c.id)), [catalog, selected]);
  const toggle = async (id: string) => {
    const next = selected.includes(id) ? selected.filter(x => x !== id) : [...selected, id];
    setSelected(next); setSaving(true); setMessage("");
    try { await api.saveIrisCatalogSelection(next); setMessage(next.includes(id) ? "Saved" : "Saved"); } catch (e) { setSelected(selected); setMessage(e instanceof Error ? e.message : "Unable to save."); } finally { setSaving(false); }
  };
  const reset = () => { setSaving(true); setMessage(""); api.getIrisCatalog().then(data => data.standard?.capability_ids ?? []).then(standard => { setSelected(standard); return api.saveIrisCatalogSelection(standard); }).then(() => setMessage("Iris Standard restored")).catch(() => setMessage("Unable to save standard.")).finally(() => setSaving(false)); };
  return <div className="iis-screen">
    <div className="iis-hero"><div className="iis-hero-top"><span>IRIS · INTELLIGENCE PRODUCTS</span>{go && <button type="button" className="iis-back" onClick={() => go("iris")}>← Iris Command</button>}</div><h1>Choose the intelligence products you want active</h1><p>Every Iris product in the catalog can be activated or deactivated independently. There is no 10-product ceiling. Your selection controls the products you want surfaced; it does not limit Iris's deeper reasoning or composition capability.</p></div>
    <div className="iis-metric-grid"><div className="iis-metric"><span>Active products</span><strong>{selected.length} / {catalog.length || "—"}</strong><small>{saving ? "Saving…" : message || "Your active Iris products"}</small></div><div className="iis-metric"><span>Round-Ups</span><strong>{selected.includes("roundups") ? "ON" : "OFF"}</strong><small>Intelligence Roundup product</small></div><div className="iis-metric"><span>Available</span><strong>{catalog.length || "—"}</strong><small>Named Iris products</small></div><div className="iis-metric"><span>Activation</span><strong>Independent</strong><small>Any number may be active</small></div></div>
    <section className="iis-panel"><header><div><span>ACTIVE PRODUCTS</span><h2>{active.length} active</h2></div><button type="button" onClick={reset} disabled={saving}>Reset to Iris Standard</button></header><p className="iis-note">Tap any active product to deactivate it. Tap any available product to activate it. Products can be combined freely; activating a product never fabricates or creates provider data.</p><div className="iis-catalog-grid">{active.map(c => <button type="button" key={c.id} className="iis-catalog-card selected" onClick={() => toggle(c.id)}><div><span>{c.family} · {c.depth}</span><b>{c.name}</b></div><small>{c.description}</small><em>Active · Tap to deactivate</em></button>)}</div>{!active.length && <div className="iis-note">No Iris products are active. Activate any products below.</div>}</section>
    <section className="iis-panel"><header><div><span>AVAILABLE PRODUCTS</span><h2>Explore and activate Iris products</h2></div></header><div className="iis-catalog-toolbar"><input aria-label="Search Iris products" placeholder="Search Iris products…" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Filter Iris product family" value={family} onChange={e => setFamily(e.target.value)}><option value="all">All families</option>{families.map(f => <option key={f} value={f}>{f}</option>)}</select></div><div className="iis-catalog-grid">{visible.map(c => { const isSelected = selected.includes(c.id); return <button type="button" key={c.id} className={`iis-catalog-card${isSelected ? " selected" : ""}`} onClick={() => toggle(c.id)}><div><span>{c.family} · {c.depth}</span><b>{c.name}</b></div><small>{c.description}</small><em>{isSelected ? "Active · Tap to deactivate" : "Inactive · Tap to activate"}</em></button>; })}</div></section>
    <section className="iis-panel"><header><div><span>THE EMPOWERMENT LAYER</span><h2>Decision Lab</h2></div><button type="button" onClick={() => go?.("iris/decision-lab")}>Open Decision Lab →</button></header><div className="iis-boundary"><p><strong>Decide with evidence.</strong> Test a hypothetical against real observed evidence before acting. Iris exposes assumptions, constraints, projected consequences, tradeoffs, uncertainty, and what evidence could change the conclusion. Simulation never pretends a hypothetical happened and never moves money.</p></div></section>
  </div>;
}
