import { FormEvent, useEffect, useRef, useState } from "react";
import { api } from "../api/backend";
import { supabase } from "../api/supabase";
import { IrisMark } from "./IrisMark";
import "../styles/iris-assistant.css";

type Message={role:"iris"|"user";text:string;state?:string};
type Position={x:number;y:number};
const starters=["What's happening with my money?","Why did my spending change?","How much is safe to spend?","Explain my cash flow","What does Plaid Transactions do?"];
const isPlaidQuestion=(q:string)=>/\bplaid\b|financial institution connection|plaid product|plaid service|plaid api|plaid link|item state|plaid check/i.test(q);
const STORAGE_KEY="ibag.iris.assistant.position.v3";

export function IrisAssistant(){
 const [open,setOpen]=useState(false);const [question,setQuestion]=useState("");const [busy,setBusy]=useState(false);const [messages,setMessages]=useState<Message[]>([]);const [position,setPosition]=useState<Position|null>(null);const drag=useRef<{dx:number;dy:number;pointerId:number}|null>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){const p=JSON.parse(saved);if(Number.isFinite(p.x)&&Number.isFinite(p.y))setPosition(p);}}catch{}},[]);
 useEffect(()=>{if(position)try{localStorage.setItem(STORAGE_KEY,JSON.stringify(position));}catch{}},[position]);
 useEffect(()=>{const clamp=()=>{setPosition(p=>{if(!p)return p;const width=Math.min(430,Math.max(0,window.innerWidth-16));const height=Math.min(620,Math.max(0,window.innerHeight-90));const x=Math.max(8,Math.min(Math.max(8,window.innerWidth-width-8),p.x));const y=Math.max(8,Math.min(Math.max(8,window.innerHeight-height-8),p.y));return x===p.x&&y===p.y?p:{x,y};});};const move=(e:PointerEvent)=>{if(!drag.current||e.pointerId!==drag.current.pointerId)return;e.preventDefault();const width=Math.min(430,window.innerWidth-16);const height=Math.min(620,window.innerHeight-90);const x=Math.max(8,Math.min(window.innerWidth-width-8,e.clientX-drag.current.dx));const y=Math.max(8,Math.min(window.innerHeight-height-8,e.clientY-drag.current.dy));setPosition({x,y});};const up=(e:PointerEvent)=>{if(!drag.current||e.pointerId!==drag.current.pointerId)return;drag.current=null;document.body.style.userSelect="";document.body.style.overflow="";};const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(false);};window.addEventListener("pointermove",move,{passive:false});window.addEventListener("pointerup",up);window.addEventListener("pointercancel",up);window.addEventListener("resize",clamp);window.addEventListener("keydown",key);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);window.removeEventListener("pointercancel",up);window.removeEventListener("resize",clamp);window.removeEventListener("keydown",key);};},[]);
 async function ask(value=question){const text=value.trim();if(!text||busy)return;setQuestion("");setOpen(true);setMessages(m=>[...m,{role:"user",text}]);setBusy(true);try{
   if(isPlaidQuestion(text)){
    const {data}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_BACKEND_URL}/iris/plaid-knowledge`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({question:text})});if(!r.ok)throw new Error("Iris could not retrieve Plaid public knowledge");const result=await r.json();const records=result.records??[];const answer=records.length?`I found ${records.length} relevant official-public Plaid knowledge record${records.length===1?"":"s"}. ${records.slice(0,5).map((x:any)=>`${x.name}: ${x.description} How: ${x.how_it_works} Iris mapping: ${(x.iris_capabilities??[]).join(", ")||"none"}.`).join(" ")} This is educational product knowledge, not evidence that the capability or its data was observed for your account.`:"I do not currently have a matching public Plaid knowledge record. I will not invent a product or service description.";setMessages(m=>[...m,{role:"iris",text:answer,state:"public Plaid knowledge"}]);
   }else{const result=await api.askIris(text,{surface:window.location.pathname});setMessages(m=>[...m,{role:"iris",text:result.answer,state:result.evidence_state}]);}
  }catch(error){setMessages(m=>[...m,{role:"iris",text:error instanceof Error?error.message:"Iris could not complete that question."}]);}finally{setBusy(false);}}
 function submit(event:FormEvent){event.preventDefault();void ask();}
 function startDrag(e:React.PointerEvent){if((e.target as HTMLElement).closest("[data-iris-close],input"))return;e.preventDefault();const rect=e.currentTarget.getBoundingClientRect();drag.current={dx:e.clientX-rect.left,dy:e.clientY-rect.top,pointerId:e.pointerId};document.body.style.userSelect="none";document.body.style.overflow="hidden";(e.currentTarget as HTMLElement).setPointerCapture?.(e.pointerId);}
 const moveByKeyboard=(e:React.KeyboardEvent)=>{if(!position)return;const step=24;let dx=0,dy=0;if(e.key==="ArrowLeft")dx=-step;if(e.key==="ArrowRight")dx=step;if(e.key==="ArrowUp")dy=-step;if(e.key==="ArrowDown")dy=step;if(!dx&&!dy)return;e.preventDefault();const width=Math.min(430,window.innerWidth-16);const height=Math.min(620,window.innerHeight-90);setPosition({x:Math.max(8,Math.min(window.innerWidth-width-8,position.x+dx)),y:Math.max(8,Math.min(window.innerHeight-height-8,position.y+dy))});};
 const toggle=()=>setOpen(v=>!v);
 const panelStyle=position?{left:position.x,top:position.y,right:"auto",bottom:"auto"}:undefined;
 const orbStyle={right:24,bottom:86};
 return <><button className="iris-assistant-orb" style={orbStyle} onClick={toggle} aria-label={open?"Close Iris":"Open Iris"} aria-expanded={open}><span className="iris-assistant-orb-core"><IrisMark size={27} color="#fff"/></span><span>Iris</span><i className={open?"open":""}/></button>{open&&<section className="iris-assistant" style={panelStyle} aria-label="Iris financial assistant"><header onPointerDown={startDrag}><button type="button" className="iris-assistant-drag-handle" aria-label="Move Iris" onPointerDown={startDrag} onClick={e=>e.preventDefault()} onKeyDown={moveByKeyboard}><span/><span/><span/></button><div className="iris-assistant-title"><IrisMark size={24} color="#fff"/><div><strong>Iris</strong><small>Your financial intelligence</small></div></div><div className="iris-assistant-window-actions"><span className="iris-assistant-drag-label">MOVE</span><button data-iris-close type="button" onPointerDown={e=>e.stopPropagation()} onClick={()=>setOpen(false)} aria-label="Close Iris">×</button></div></header><div className="iris-assistant-body">{!messages.length&&<div className="iris-assistant-welcome"><span>ASK IRIS ANYTHING</span><h2>What do you want to understand?</h2><p>Ask about your observed financial evidence, Iris interpretations, or publicly documented Plaid products and services.</p><div className="iris-assistant-starters">{starters.map(s=><button key={s} onClick={()=>void ask(s)}>{s}</button>)}</div></div>}{messages.map((m,i)=><div key={i} className={`iris-assistant-message ${m.role}`}><div>{m.text}</div>{m.role==="iris"&&<small>{m.state?`${m.state.replace(/_/g," ")} · evidence-grounded`:"Iris"}</small>}</div>)}{busy&&<div className="iris-assistant-message iris"><div className="iris-assistant-thinking"><i/><i/><i/></div><small>Reasoning from available evidence…</small></div>}</div><form onSubmit={submit} className="iris-assistant-input"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ask Iris…" maxLength={2000}/><button disabled={busy||!question.trim()}>Ask</button></form></section>}</>;
}
