import { useEffect, useState } from "react";
import { api } from "../api/backend";
import { PlaidLinkButton } from "./PlaidLink";

type Props = { page?: string; go?: (page: string) => void };
const surfaces = [
  ["iris", "Command", "What Iris can currently establish from governed evidence."],
  ["iris/state", "Financial State", "Observed and derived financial state."],
  ["iris/cash-flow", "Cash Flow", "Observed inflows, outflows, liquidity and pressure."],
  ["iris/spending", "Spending", "Observed spending structure, change and relationships."],
  ["iris/evidence", "Evidence", "Evidence, provenance, lineage and uncertainty."],
  ["iris/intelligence", "Intelligence", "Internal recursive intelligence status and outputs."],
  ["iris/behavior", "Behavior", "Observed recurrence, patterns, changes and anomalies."],
  ["iris/reasoning", "Reasoning", "Relationships, causal boundaries and investigations."],
  ["iris/decisions", "Decisions", "Evidence-linked decision and consequence analysis."],
  ["iris/simulation", "Simulation", "Explicitly hypothetical scenarios and counterfactuals."],
  ["iris/catalog", "Report Catalog", "User products: reports and analytics."],
] as const;
const money = (n: unknown) => { const v = typeof n === "number" ? n : Number(n); return n == null || !Number.isFinite(v) ? "—" : `${v < 0 ? "−" : ""}$${Math.abs(v).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; };
const count = (v: unknown) => Array.isArray(v) ? String(v.length) : v == null ? "—" : typeof v === "object" ? String(Object.keys(v as object).length) : String(v);
const label = (v: unknown) => String(v ?? "—").replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
function Evidence({ value }: { value?: string }) { const v = value ?? "insufficient_evidence"; const names: Record<string, string> = { observed: "Observed", calculated: "Calculated", inferred: "Iris inference", limited: "Limited evidence", insufficient_evidence: "Insufficient evidence" }; return <span className={`iris4-evidence ${v}`}>{names[v] ?? label(v)}</span>; }
function Card({ title, value, note, evidence }: { title: string; value: unknown; note?: string; evidence?: string }) { const displayValue = value == null ? "—" : typeof value === "object" ? count(value) : String(value); return <article className="iris-surface-card"><span>{title}</span><strong>{displayValue}</strong>{note && <small>{note}</small>}{evidence && <Evidence value={evidence}/>}</article>; }

export function IrisCommandSurface({ page = "iris", go }: Props) {
  const [intel, setIntel] = useState<any>(null), [overview, setOverview] = useState<any>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true), [runLoading, setRunLoading] = useState(false), [runMessage, setRunMessage] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const o = await api.getOverview(); setOverview(o); if (o?.accounts?.length) setIntel(await api.getIntelligence()); } catch (e) { setError(e instanceof Error ? e.message : "Iris could not load observed financial data"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const runIris = async () => { if (runLoading) return; setRunLoading(true); setRunMessage(null); setError(null); try { const run = await api.runIris(); setRunMessage(`Iris execution ${run?.status ?? "accepted"}.`); if (run?.status === "CERTIFIED") await load(); } catch (e) { setError(e instanceof Error ? e.message : "Iris execution could not be started"); } finally { setRunLoading(false); } };
  const surface = surfaces.find(s => s[0] === page) ?? surfaces[0];
  if (page === "iris/catalog") return <main className="iris4-screen"><div className="iris4-body"><p>Report Catalog is available from the main application control.</p></div></main>;
  return <main className="iris4-screen"><header className="iris4-hero"><div><span>IRIS · {surface[1]}</span><h1>{surface[1]}</h1><p>{surface[2]}</p></div><div className="iris4-status"><b>Evidence</b> {intel?.intelligence_gate?.status ?? (loading ? "loading" : "constrained")}<i/><b>Higher-order</b> {intel?.intelligence_gate?.higher_order_conclusions_enabled ? "enabled" : "evidence-gated"}<i/><b>Updated</b> {intel?.generated_at ? new Date(intel.generated_at).toLocaleTimeString() : "—"}</div><div className="iris-connect-control"><button type="button" onClick={() => void runIris()} disabled={runLoading}>{runLoading ? "Running Iris…" : "Run Iris intelligence"}</button><PlaidLinkButton onSuccess={() => void load()}/></div></header><div className="iris4-layout"><nav className="iris4-nav">{surfaces.filter(s => s[0] !== "iris/catalog").map(s => <button key={s[0]} className={surface[0] === s[0] ? "active" : ""} onClick={() => go?.(s[0])}><strong>{s[1]}</strong><span>{s[2]}</span></button>)}<button className={page === "iris/catalog" ? "active" : ""} onClick={() => go?.("iris/catalog")}><strong>Report Catalog</strong><span>Activate or deactivate Iris reports and analytics.</span></button></nav><section className="iris4-body">{runMessage && <section className="iris-surface"><span className="eyebrow">IRIS EXECUTION</span><p>{runMessage}</p></section>}{error && <section className="iris-surface"><span className="eyebrow">EVIDENCE STATUS</span><h2>Iris remains evidence-gated</h2><p>{error}</p><p>Iris will not invent missing financial facts.</p></section>}{page === "iris" ? <Command intel={intel} overview={overview} loading={loading}/> : <Surface page={page} intel={intel} overview={overview} loading={loading}/>}</section></div></main>;
}
function Command({ intel, overview, loading }: { intel: any; overview: any; loading: boolean }) { return <><section className="iris-surface"><span className="eyebrow">LIVE READOUT</span><h2>Evidence before conclusions</h2><p>Iris separates provider observations, calculations, inference, scenarios and unknowns. Empty evidence is never converted into a financial value.</p><div className="iris-metric-grid"><Card title="Liquid position" value={intel?.net_worth?.liquid_assets != null ? money(intel.net_worth.liquid_assets) : "—"} evidence="calculated"/><Card title="Cash flow" value={money(intel?.cash_flow?.net)} evidence="calculated"/><Card title="Revolving debt" value={money(intel?.debt_health?.revolving_debt)} evidence={intel?.debt_health?.revolving_debt == null ? "insufficient_evidence" : "calculated"}/><Card title="Accounts" value={count(overview?.accounts)} evidence="observed"/><Card title="Analytical definitions" value={count(intel?.intelligence_atlas?.definitions)} note="Internal intelligence machinery"/><Card title="Higher-order findings" value={count(intel?.higher_order_synthesis?.findings)} evidence={intel?.higher_order_synthesis?.findings?.length ? "inferred" : "insufficient_evidence"}/></div>{loading && <p>Reading observed financial evidence…</p>}</section><section className="iris-surface"><span className="eyebrow">USER PRODUCTS</span><h2>Reports & analytics</h2><p>The intelligence hierarchy creates the analytical results. The report catalog is the product layer users control. Activate or deactivate individual reports without changing the underlying intelligence hierarchy.</p><button type="button" onClick={() => window.location.hash = "workspace/iris/catalog"}>Open Report Catalog →</button></section></>; }
function Surface({ page, intel, overview, loading }: { page: string; intel: any; overview: any; loading: boolean }) { const data: Record<string, Array<[string, unknown]>> = { "iris/state": [["Liquid assets", money(intel?.net_worth?.liquid_assets)], ["Revolving debt", money(intel?.debt_health?.revolving_debt)], ["Credit utilization", intel?.debt_health?.credit_utilization == null ? "—" : `${(intel.debt_health.credit_utilization * 100).toFixed(0)}%`], ["Accounts", count(overview?.accounts)]], "iris/cash-flow": [["Inflows", money(intel?.cash_flow?.inflow)], ["Outflows", money(intel?.cash_flow?.outflow)], ["Net flow", money(intel?.cash_flow?.net)], ["Safe to spend", money(intel?.cash_flow_safety?.safeToSpend)]], "iris/spending": [["Domains", count(intel?.spending_by_domain)], ["Category changes", count(intel?.category_drift)], ["Anomalies", count(intel?.anomalies)]], "iris/evidence": [["Gate", label(intel?.intelligence_gate?.status)], ["Source fidelity", label(intel?.source_fidelity?.status ?? intel?.source_fidelity?.state)], ["Provider lineage", count(intel?.provider_lineage)], ["Uncertainty", count(intel?.uncertainty)]], "iris/intelligence": [["Analytical definitions", count(intel?.intelligence_atlas?.definitions)], ["Composition findings", count(intel?.intelligence_composition?.findings)], ["Higher-order findings", count(intel?.higher_order_synthesis?.findings)]], "iris/behavior": [["Recurrence", count(intel?.recurring_series ?? intel?.recurring)], ["Category changes", count(intel?.category_drift)], ["Anomalies", count(intel?.anomalies)]], "iris/reasoning": [["Reasoning", count(intel?.reasoning)], ["Causal analysis", count(intel?.causal_analysis)], ["Investigations", count(intel?.investigations)]], "iris/decisions": [["Decision intelligence", count(intel?.decision_intelligence)], ["Decision graph", count(intel?.decision_graph)], ["Goals", count(intel?.goals)]], "iris/simulation": [["Counterfactual intelligence", count(intel?.counterfactual_intelligence)], ["Execution state", intel?.counterfactual_intelligence?.execution_state ?? "—"]], }; const cards = data[page] ?? []; return <section className="iris-surface"><span className="eyebrow">LIVE INTELLIGENCE SURFACE</span><h2>{surfaces.find(s => s[0] === page)?.[1] ?? "Iris"}</h2><p>{loading ? "Reading observed financial evidence…" : "Live output from the governed Iris runtime. Unsupported or unavailable values remain explicitly bounded."}</p><div className="iris-metric-grid">{cards.map(([title, value]) => <Card key={title} title={title} value={value}/>)}</div></section>; }
