import { FormEvent, useEffect, useRef, useState } from "react";
import { api } from "../api/backend";
import { supabase } from "../api/supabase";
import { IrisMark } from "./IrisMark";
import "../styles/iris-assistant.css";

type Message={role:"iris"|"user";text:string;state?:string};
type Position={x:number;y:number};
type Mode="financial"|"intelligence";
type Props={mode?:Mode};

const financialStarters=["What's happening with my money?","Why did my spending change?","How much is safe to spend?","Explain my cash flow","Show me the evidence"];
const intelligenceStarters=["Explain the intelligence hierarchy","How does IRIS reason from evidence?","What is recursive intelligence?","Explain forward and reverse lineage","Why isn't unknown the same as zero?"];
const isPlaidQuestion=(q:string)=>/\bplaid\b|financial institution connection|plaid product|plaid service|plaid api|plaid link|item state|plaid check/i.test(q);
const STORAGE_KEY="iris.assistant.position.v2";

function educationalAnswer(question:string){
 const q=question.toLowerCase();
 if(/unknown|zero|missing|unavailable/.test(q)) return "IRIS keeps epistemic states separate: an unknown or unavailable value is not zero. A zero is meaningful only when governed evidence actually establishes zero. Missing evidence stays explicitly missing or limited.";
 if(/recursive|higher.?order|depth|infinite|unbounded/.test(q)) return "IRIS has no artificial semantic hierarchy depth ceiling. Higher-order intelligence can consume valid upstream intelligence, preserve exact lineage, and become an input to further composition. Operational resource limits may constrain materialization, but they do not define the meaning of the hierarchy.";
 if(/lineage|forward|reverse|travers/.test(q)) return "Forward traversal follows evidence into canonical state, intelligence, and results. Reverse traversal starts with a result or intelligence node and traces its exact upstream nodes, evidence boundary, and source observations. Both directions must remain ownership- and execution-bound and cycle-safe.";
 if(/evidence|observe|observation|plaid/.test(q)) return "IRIS treats provider observations as evidence, not as conclusions. Availability, consent, authorization, provider response, persistence, certification, intelligence consumption, and actual use are separate states. Intelligence may only claim what its governed evidence and lineage support.";
 if(/domain|authentication|transaction|balance|identity|asset|liabilit|investment|statement/.test(q)) return "The architectural Level-2 evidence domains are Authentication, Transactions, Balance, Identity, Assets, Liabilities, Investments, and Statements. Statements is architecturally defined but deferred from the current Sandbox runtime boundary until real banking.";
 if(/causal|correlation|predict|scenario|counterfactual/.test(q)) return "IRIS preserves epistemic boundaries: correlation is not causation, prediction is not observation, and a scenario is not an observed fact. Stronger claims require stronger evidence, appropriate transformations, preserved uncertainty, and certification.";
 if(/graph|tree|parent|relationship/.test(q)) return "The intelligence hierarchy is a graph rather than a simple tree. A node can have multiple upstream relationships, span domains, participate in temporal relationships, and feed higher-order compositions. The graph is the reasoning machinery, not the user product catalog.";
 return "I’m here to explain how IRIS understands financial reality: evidence is governed first, intelligence is composed from what that evidence supports, and results remain connected to the reasoning and lineage that produced them. Ask me about the hierarchy, evidence, graph, lineage, or any concept on this page.";
}

export function IrisAssistant({mode="financial"}:Props){
 const [open,setOpen]=useState(false);const [question,setQuestion]=useState("");const [busy,setBusy]=useState(false);const [messages,setMessages]=useState<Message[]>([]);const [position,setPosition]=useState<Position|null>(null);const drag=useRef<{dx:number;dy:number}|null>(null);
 const educational=mode==="intelligence";
 const starters=educational?intelligenceStarters:financialStarters;
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setPosition(JSON.parse(saved));}catch{}},[]);
 useEffect(()=>{if(position)try{localStorage.setItem(STORAGE_KEY,JSON.stringify(position));}catch{}},[position]);
 useEffect(()=>{const move=(e:PointerEvent)=>{if(!drag.current)return;const width=Math.min(430,window.innerWidth-28);const height=Math.min(680,window.innerHeight-120);const x=Math.max(8,Math.min(window.innerWidth-width-8,e.clientX-drag.current.dx));const y=Math.max(8,Math.min(window.innerHeight-height-8,e.clientY-drag.current.dy));setPosition({x,y});};const up=()=>{drag.current=null;document.body.style.userSelect="";};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up);return()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up);};},[]);
 async function ask(value=question){const text=value.trim();if(!text||busy)return;setQuestion("");setOpen(true);setMessages(m=>[...m,{role:"user",text}]);setBusy(true);try{
   if(educational){
     setMessages(m=>[...m,{role:"iris",text:educationalAnswer(text),state:"educational · no user data"}]);
   }else if(isPlaidQuestion(text)){
     const {data}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_BACKEND_URL}/iris/plaid-knowledge`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({question:text})});if(!r.ok)throw new Error("Iris could not retrieve Plaid public knowledge");const result=await r.json();const records=result.records??[];const answer=records.length?`I found ${records.length} relevant official-public Plaid knowledge record${records.length===1?"":"s"}. ${records.slice(0,5).map((x:any)=>`${x.name}: ${x.description} How: ${x.how_it_works} Iris mapping: ${(x.iris_capabilities??[]).join(", ")||"none"}.`).join(" ")} This is educational product knowledge, not evidence that the capability or its data was observed for your account.`:"I do not currently have a matching public Plaid knowledge record. I will not invent a product or service description.";setMessages(m=>[...m,{role:"iris",text:answer,state:"public Plaid knowledge"}]);
   }else{const result=await api.askIris(text,{surface:window.location.pathname});setMessages(m=>[...m,{role:"iris",text:result.answer,state:result.evidence_state}]);}
  }catch(error){setMessages(m=>[...m,{role:"iris",text:error instanceof Error?error.message:"Iris could not complete that question."}]);}finally{setBusy(false);}}
 function submit(event:FormEvent){event.preventDefault();void ask();}
 function startDrag(e:React.PointerEvent){if((e.target as HTMLElement).closest("button"))return;const rect=e.currentTarget.getBoundingClientRect();drag.current={dx:e.clientX-rect.left,dy:e.clientY-rect.top};document.body.style.userSelect="none";}
 const panelStyle=position?{left:position.x,top:position.y,right:"auto",bottom:"auto"}:undefined;
 return <><button className="iris-assistant-orb" onClick={()=>setOpen(!open)} aria-label={open?"Close Iris":"Open Iris"}><span className="iris-assistant-orb-core"><IrisMark size={27} color="#fff"/></span><span>Iris</span><i className={open?"open":""}/></button>{open&&<section className="iris-assistant" style={panelStyle} aria-label={educational?"Iris intelligence guide":"Iris financial assistant"}><header onPointerDown={startDrag}><div className="iris-assistant-title"><IrisMark size={24} color="#fff"/><div><strong>Iris</strong><small>{educational?"Intelligence guide · educational mode":"Your financial intelligence"}</small></div></div><div className="iris-assistant-window-actions"><span className="iris-assistant-drag-label">MOVE</span><button onClick={()=>setOpen(false)} aria-label="Close Iris">×</button></div></header><div className="iris-assistant-body">{!messages.length&&<div className="iris-assistant-welcome"><span>{educational?"ASK IRIS · LEARN":"ASK IRIS · HELP & ASSIST"}</span><h2>{educational?"What do you want to understand about IRIS?":"What do you want help with?"}</h2><p>{educational?"I’m ready to explain the intelligence hierarchy, evidence, graph, lineage and recursive reasoning. No user financial data is loaded in this educational mode.":"I’m ready to help you understand your financial life, results, reports and evidence. I’ll keep every answer grounded in what IRIS can actually establish."}</p><div className="iris-assistant-starters">{starters.map(s=><button key={s} onClick={()=>void ask(s)}>{s}</button>)}</div></div>}{messages.map((m,i)=><div key={i} className={`iris-assistant-message ${m.role}`}><div>{m.text}</div>{m.role==="iris"&&<small>{m.state?m.state.replace(/_/g," "):"Iris"}</small>}</div>)}{busy&&<div className="iris-assistant-message iris"><div className="iris-assistant-thinking"><i/><i/><i/></div><small>{educational?"Explaining the intelligence model…":"Reasoning from available evidence…"}</small></div>}</div><form onSubmit={submit} className="iris-assistant-input"><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder={educational?"Ask Iris to explain…":"Ask Iris…"} maxLength={2000}/><button disabled={busy||!question.trim()}>Ask</button></form></section>}</>;
}
