import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { api } from "../api/backend";
import { PlaidLinkButton } from "./PlaidLink";

const pageNames = ["overview", "money", "cashflow", "spending", "activity", "data", "intelligence", "evidence"] as const;
type Page = typeof pageNames[number];
type AnyRecord = Record<string, any>;

const label = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const money = (value: unknown) => { const n = Number(value); return value == null || !Number.isFinite(n) ? "—" : `${n < 0 ? "−" : ""}$${Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; };
const evidenceLabel = (value: unknown) => ({ observed: "Observed", calculated: "Calculated", inferred: "Iris inference", limited: "Limited evidence", insufficient_evidence: "Insufficient evidence" } as AnyRecord)[String(value)] ?? label(String(value ?? "unknown"));
const protectedKey = (key: string) => /access.?token|refresh.?token|secret|api.?key|client.?secret|password|authorization/i.test(key);

function Evidence({ state = "calculated" }: { state?: string }) { return <span style={{ fontSize: 11, opacity: .72 }}>{evidenceLabel(state)}</span>; }
function Metric({ name, value, note, state = "calculated" }: { name: string; value: ReactNode; note?: string; state?: string }) { return <article style={{ border: "1px solid rgba(255,255,255,.10)", borderRadius: 14, padding: 16, background: "rgba(255,255,255,.025)" }}><span style={{ display: "block", fontSize: 11, opacity: .62, textTransform: "uppercase", letterSpacing: ".08em" }}>{name}</span><strong style={{ display: "block", marginTop: 8, fontSize: 24 }}>{value}</strong>{note && <small style={{ display: "block", marginTop: 5, opacity: .55 }}>{note}</small>}<Evidence state={state}/></article>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section style={{ marginTop: 22 }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 10 }}><h2 style={{ margin: 0, fontSize: 13, letterSpacing: ".10em", textTransform: "uppercase", opacity: .78 }}>{title}</h2></div>{children}</section>; }

function Tree({ value, path = "root", depth = 0 }: { value: unknown; path?: string; depth?: number }) {
  if (value === null || value === undefined) return <span style={{ opacity: .45 }}>Not available in observed evidence</span>;
  if (typeof value !== "object") return <span>{typeof value === "number" ? value.toLocaleString("en-US", { maximumFractionDigits: 8 }) : String(value)}</span>;
  const entries = Array.isArray(value) ? value.map((item, index) => [String(index), item] as const) : Object.entries(value as AnyRecord);
  return <div style={{ display: "grid", gap: 4, marginLeft: depth ? 10 : 0 }}>{entries.map(([key, child]) => { if (protectedKey(key)) return null; const complex = child !== null && typeof child === "object"; const next = `${path}.${key}`; return complex ? <details key={next} open={depth < 1} style={{ borderLeft: "1px solid rgba(255,255,255,.08)", paddingLeft: 10 }}><summary style={{ cursor: "pointer", opacity: .82 }}>{label(key)}</summary><Tree value={child} path={next} depth={depth + 1}/></details> : <div key={next} style={{ display: "grid", gridTemplateColumns: "minmax(160px, .7fr) minmax(180px, 1.3fr)", gap: 10, padding: "5px 0", borderBottom: "1px solid rgba(255,255,255,.04)" }}><span style={{ opacity: .55 }}>{label(key)}</span><span style={{ overflowWrap: "anywhere" }}><Tree value={child} path={next} depth={depth + 1}/></span></div>; })}</div>;
}

function Connect({ onSuccess }: { onSuccess: () => void }) { return <div style={{ minHeight: "72vh", display: "grid", placeItems: "center", padding: 28 }}><div style={{ maxWidth: 620, textAlign: "center" }}><span style={{ fontSize: 11, letterSpacing: ".14em", opacity: .6 }}>IRIS · CONNECTION</span><h1 style={{ fontSize: 42, margin: "14px 0 12px" }}>Connect your financial accounts.</h1><p style={{ opacity: .65, lineHeight: 1.7 }}>Iris can only reason from financial evidence that has actually been authorized and received. Plaid Link is used only to establish the connection; your financial data is stored and presented from Supabase.</p><PlaidLinkButton onSuccess={onSuccess}/><p style={{ fontSize: 12, opacity: .42, marginTop: 16 }}>No connection means no financial facts, no synthetic values and no invented analysis.</p></div></div>; }

function Overview({ o, i, go }: { o: AnyRecord; i: AnyRecord; go: (page: Page) => void }) { const s = i?.cash_flow_safety; const c = i?.cash_flow; const n = i?.net_worth?.liquid_assets; return <div><Section title="Current financial state"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 10 }}><Metric name="Liquid position" value={money(n)} note="Connected financial evidence" state={n == null ? "insufficient_evidence" : "calculated"}/><Metric name="Safe to spend" value={money(s?.safeToSpend)} note={s?.horizonDays ? `${s.horizonDays}-day calculated horizon` : undefined}/><Metric name="Cash flow" value={money(c?.net)} note="Observed economic flow, transfers excluded"/><Metric name="Revolving debt" value={money(i?.debt_health?.revolvingDebt)} note="Liability evidence"/></div></Section><Section title="Iris priority"><div style={{ padding: 20, borderRadius: 14, border: "1px solid rgba(255,255,255,.10)" }}><strong>{i?.reasoning?.priorityFocus?.reason ?? i?.narrative ?? "No evidence-backed priority is currently available."}</strong><p style={{ opacity: .6, lineHeight: 1.6 }}>Iris separates observed facts from calculations and inferences. If evidence is insufficient, the result is constrained rather than guessed.</p><button onClick={() => go("intelligence")} style={buttonStyle}>Explore intelligence →</button></div></Section><Section title="Recent observed activity"><div style={{ display: "grid", gap: 6 }}>{(o?.recent_transactions ?? []).slice(0, 8).map((tx: AnyRecord) => <div key={tx.id} style={rowStyle}><span>{tx.merchant_name ?? tx.name ?? "Transaction"}<small style={{ display: "block", opacity: .45 }}>{tx.posted_date ?? "—"} · {tx.plaid_category_detailed ?? tx.plaid_category_primary ?? "Unclassified"}</small></span><strong>{money(tx.amount)}</strong></div>)}</div></Section></div>; }

function Money({ o, i }: { o: AnyRecord; i: AnyRecord }) { return <div><Section title="Accounts and liquidity"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 10 }}><Metric name="Accounts" value={o?.accounts?.length ?? 0} note="Canonical Supabase account records" state="observed"/><Metric name="Liquid assets" value={money(i?.net_worth?.liquid_assets)} note="Calculated from canonical evidence"/><Metric name="Credit utilization" value={i?.debt_health?.creditUtilization == null ? "—" : `${(i.debt_health.creditUtilization * 100).toFixed(1)}%`} note="Calculated"/><Metric name="Revolving debt" value={money(i?.debt_health?.revolvingDebt)}/></div></Section><Section title="Connected accounts"><div style={{ display: "grid", gap: 7 }}>{(o?.accounts ?? []).map((a: AnyRecord) => <div key={a.id} style={rowStyle}><span><strong>{a.name ?? "Account"}</strong><small style={{ display: "block", opacity: .45 }}>{label(a.subtype ?? a.type ?? "account")}{a.mask ? ` · ••••${a.mask}` : ""}</small></span><strong>{money(a.current_balance ?? a.available_balance)}</strong></div>)}</div></Section></div>; }

function CashFlow({ i }: { i: AnyRecord }) { const c = i?.cash_flow; const s = i?.cash_flow_safety; return <div><Section title="Observed and calculated flow"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 10 }}><Metric name="Inflows" value={money(c?.inflow)} note={`${c?.windowDays ?? "—"}-day observed window`}/><Metric name="Outflows" value={money(c?.outflow)} note="Economic outflow"/><Metric name="Net flow" value={money(c?.net)} note="Calculated"/><Metric name="Safe to spend" value={money(s?.safeToSpend)} note="Calculated safety boundary"/></div></Section><Section title="Forward model"><div style={{ padding: 18, border: "1px solid rgba(255,255,255,.09)", borderRadius: 14 }}><p style={{ opacity: .65 }}>{i?.forward_projection?.basis ?? "There is not enough evidence for a forward model."}</p>{(i?.forward_projection?.series ?? []).filter((x: AnyRecord) => x.event).slice(0, 10).map((x: AnyRecord) => <div key={x.date} style={rowStyle}><span>{x.date}<small style={{ display: "block", opacity: .5 }}>{x.event}</small></span><strong>{money(x.balance)}</strong></div>)}</div></Section></div>; }

function Spending({ i }: { i: AnyRecord }) { const domains = i?.spending_by_domain ?? []; return <div><Section title="Spending domains"><div style={{ display: "grid", gap: 8 }}>{domains.map((d: AnyRecord) => <div key={d.key} style={rowStyle}><span>{d.label ?? label(d.key ?? "domain")}<small style={{ display: "block", opacity: .45 }}>{d.transactionCount ?? 0} observed transactions</small></span><strong>{money(d.amount)}</strong></div>)}</div></Section><Section title="Behavior and anomalies"><div style={{ display: "grid", gap: 8 }}>{(i?.category_drift ?? []).filter((x: AnyRecord) => x.significant).slice(0, 10).map((x: AnyRecord) => <div key={x.subdomainKey} style={rowStyle}><span>{x.subdomainLabel}</span><strong>{Number(x.deviationPct).toFixed(1)}%</strong></div>)}{(i?.anomalies ?? []).slice(0, 10).map((x: AnyRecord, n: number) => <div key={`${x.date}-${n}`} style={rowStyle}><span>{x.merchant ?? "Unusual activity"}<small style={{ display: "block", opacity: .45 }}>{x.date ?? "—"}</small></span><strong>{money(x.amount)}</strong></div>)}</div></Section></div>; }

function Activity({ o }: { o: AnyRecord }) { return <div><Section title="Canonical transaction observations"><div style={{ display: "grid", gap: 5 }}>{(o?.recent_transactions ?? []).map((tx: AnyRecord) => <div key={tx.id} style={rowStyle}><span>{tx.merchant_name ?? tx.name ?? "Transaction"}<small style={{ display: "block", opacity: .45 }}>{tx.posted_date ?? "—"} · {label(tx.transaction_class ?? "unclassified")}</small></span><strong>{money(tx.amount)}</strong></div>)}</div></Section></div>; }

function Data({ source }: { source: AnyRecord }) { const roots = useMemo(() => ({ canonical_supabase_data: source, lineage: source?.lineage, observations: source?.observations, calculation_audit: source?.calculation_audit }), [source]); return <div><Section title="Supabase canonical source of truth"><p style={{ opacity: .6, lineHeight: 1.6 }}>This is the application data surface. Provider observations are preserved for provenance, while Iris consumes canonical Supabase records for financial reasoning. Protected credentials are never rendered.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(170px,1fr))", gap: 10, marginBottom: 14 }}><Metric name="Canonical accounts" value={source?.counts?.accounts ?? 0} state="observed"/><Metric name="Canonical transactions" value={source?.counts?.transactions ?? 0} state="observed"/><Metric name="Raw observations" value={(source?.counts?.transaction_observations ?? 0) + (source?.counts?.balance_observations ?? 0) + (source?.counts?.liability_observations ?? 0)} state="observed"/><Metric name="Calculation records" value={source?.counts?.calculations ?? 0} state="calculated"/></div>{Object.entries(roots).map(([key, value]) => <details key={key} open={key === "canonical_supabase_data"} style={{ marginBottom: 8, padding: 12, border: "1px solid rgba(255,255,255,.08)", borderRadius: 12 }}><summary style={{ cursor: "pointer" }}>{label(key)}</summary><div style={{ marginTop: 12 }}><Tree value={value} path={key}/></div></details>)}</Section></div>; }

function Intelligence({ i }: { i: AnyRecord }) { const atlas = i?.intelligence_atlas?.definitions ?? []; const governor = i?.iris_governor; return <div><Section title="Iris — supreme intelligence"><div style={{ padding: 20, borderRadius: 14, border: "1px solid rgba(255,255,255,.11)" }}><h3 style={{ marginTop: 0 }}>Iris governs the entire intelligence system.</h3><p style={{ opacity: .6, lineHeight: 1.65 }}>Iris selects relevant evidence, composes intelligence in valid combinations and orders, validates results, explains uncertainty, monitors outcomes, learns from validated outcomes, and revalidates improvement candidates. It never silently fabricates financial evidence or mutates Supabase source truth.</p><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 10 }}><Metric name="Evidence gate" value={evidenceLabel(governor?.evidence_gate?.status)} state={governor?.evidence_gate?.ready ? "calculated" : "limited"}/><Metric name="Composition paths" value={governor?.composition_engine?.generated ?? 0} note="Runtime-materialized preview"/><Metric name="Depth ceiling" value="None" note="Resource budgets are safety limits, not intelligence limits" state="calculated"/><Metric name="Self-modification" value="Disabled" note="Candidate → validation → governed promotion" state="calculated"/></div></div></Section><Section title="Intelligence registry"><div style={{ display: "grid", gap: 7 }}>{atlas.slice(0, 80).map((d: AnyRecord) => <div key={d.id} style={rowStyle}><span><strong>{d.name}</strong><small style={{ display: "block", opacity: .45 }}>{label(d.family)} · {(d.inputs ?? []).join(", ")}</small></span><Evidence state={d.evidence_ready ? "calculated" : "limited"}/></div>)}</div></Section></div>; }

function Evidence({ source, i }: { source: AnyRecord; i: AnyRecord }) { return <div><Section title="Evidence and lineage"><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(190px,1fr))", gap: 10 }}><Metric name="Source status" value={evidenceLabel(i?.source_fidelity?.status)} state={i?.source_fidelity?.status ?? "limited"}/><Metric name="Provider lineage" value={i?.provider_lineage?.lineageComplete ? "Complete" : "Limited"} state={i?.provider_lineage?.lineageComplete ? "calculated" : "limited"}/><Metric name="Display source" value="Supabase" note="Canonical application source" state="observed"/><Metric name="Protected secrets" value="Withheld" state="calculated"/></div></Section><Section title="Reverse lineage"><div style={{ padding: 18, border: "1px solid rgba(255,255,255,.08)", borderRadius: 14 }}><p style={{ opacity: .62 }}>Every displayed value and intelligence result must be traversable back through API output and intelligence dependencies to the canonical Supabase field and, where applicable, the preserved provider observation.</p><Tree value={source?.lineage ?? i?.evidence_graph} path="reverse_lineage"/></div></Section></div>; }

const buttonStyle: React.CSSProperties = { border: "1px solid rgba(255,255,255,.13)", background: "rgba(255,255,255,.045)", color: "inherit", borderRadius: 9, padding: "9px 12px", cursor: "pointer" };
const rowStyle: React.CSSProperties = { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 16, padding: "11px 13px", border: "1px solid rgba(255,255,255,.07)", borderRadius: 10, background: "rgba(255,255,255,.018)" };

export function IrisWorkspaceV2() {
  const [page, setPage] = useState<Page>("overview");
  const [overview, setOverview] = useState<AnyRecord | null>(null);
  const [intelligence, setIntelligence] = useState<AnyRecord | null>(null);
  const [source, setSource] = useState<AnyRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const o = await api.getOverview(); setOverview(o); if (o?.accounts?.length) setIntelligence(await api.getIntelligence()); else setIntelligence(null); setSource(await api.getSourceTruth(500)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load Iris"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", background: "#07090e", color: "#fff" }}>Reading canonical Supabase evidence…</div>;
  if (error && !overview) return <div style={{ minHeight: "100vh", display: "grid", placeItems: "center", background: "#07090e", color: "#fff" }}><div><strong>Iris could not load the canonical data surface.</strong><p style={{ opacity: .6 }}>{error}</p><button style={buttonStyle} onClick={() => void load()}>Retry</button></div></div>;
  if (!overview?.accounts?.length) return <div style={{ minHeight: "100vh", background: "#07090e", color: "#fff" }}><Connect onSuccess={() => void load()}/></div>;
  const render = page === "overview" ? <Overview o={overview} i={intelligence ?? {}} go={setPage}/> : page === "money" ? <Money o={overview} i={intelligence ?? {}}/> : page === "cashflow" ? <CashFlow i={intelligence ?? {}}/> : page === "spending" ? <Spending i={intelligence ?? {}}/> : page === "activity" ? <Activity o={overview}/> : page === "data" ? <Data source={source ?? {}}/> : page === "intelligence" ? <Intelligence i={intelligence ?? {}}/> : <Evidence source={source ?? {}} i={intelligence ?? {}}/>;
  return <div style={{ minHeight: "100vh", background: "#07090e", color: "#fff", fontFamily: "Inter,system-ui,sans-serif" }}><aside style={{ position: "fixed", inset: "0 auto 0 0", width: 210, padding: 20, borderRight: "1px solid rgba(255,255,255,.07)", background: "rgba(7,9,14,.98)" }}><button onClick={() => setPage("overview")} style={{ ...buttonStyle, width: "100%", textAlign: "left", marginBottom: 20 }}><strong>iBag</strong><small style={{ display: "block", opacity: .5, marginTop: 4 }}>Financial intelligence by Iris</small></button><nav style={{ display: "grid", gap: 5 }}>{pageNames.map(p => <button key={p} onClick={() => setPage(p)} style={{ ...buttonStyle, textAlign: "left", background: page === p ? "rgba(255,255,255,.10)" : "transparent" }}>{label(p)}</button>)}</nav><div style={{ position: "absolute", bottom: 20, left: 20, right: 20, fontSize: 11, opacity: .45 }}>Supabase source of truth<br/>Plaid connection only<br/>Evidence-gated · read-only</div></aside><main style={{ marginLeft: 210, minHeight: "100vh", padding: "28px 5vw 80px", maxWidth: 1300 }}><header style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, borderBottom: "1px solid rgba(255,255,255,.07)", paddingBottom: 18 }}><div><span style={{ fontSize: 10, letterSpacing: ".14em", opacity: .5 }}>IRIS / {label(page)}</span><h1 style={{ margin: "7px 0 0", fontSize: 30 }}>{page === "overview" ? "Your financial life state" : label(page)}</h1></div><PlaidLinkButton onSuccess={() => void load()}/></header>{error && <div role="alert" style={{ marginTop: 14, padding: 12, border: "1px solid rgba(255,255,255,.12)", borderRadius: 10, opacity: .8 }}>{error} <button style={buttonStyle} onClick={() => void load()}>Refresh</button></div>}{render}</main></div>;
}
