import { useCallback, useEffect, useState, type ReactNode } from "react";
import { api } from "../api/backend";
import { PlaidLinkButton } from "./PlaidLink";

type Page = "overview" | "money" | "cashflow" | "spending" | "activity" | "data" | "intelligence" | "evidence";
type R = Record<string, any>;
const pages: Page[] = ["overview", "money", "cashflow", "spending", "activity", "data", "intelligence", "evidence"];
const label=(s:string)=>s.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const money=(v:unknown)=>{const n=Number(v);return v==null||!Number.isFinite(n)?"—":`${n<0?"−":""}$${Math.abs(n).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`};
const button:React.CSSProperties={border:"1px solid rgba(255,255,255,.13)",background:"rgba(255,255,255,.045)",color:"inherit",borderRadius:9,padding:"9px 12px",cursor:"pointer"};
const row:React.CSSProperties={display:"flex",justifyContent:"space-between",gap:14,alignItems:"center",padding:"11px 13px",border:"1px solid rgba(255,255,255,.07)",borderRadius:10};
function Metric({name,value,note}:{name:string;value:ReactNode;note?:string}){return <article style={{border:"1px solid rgba(255,255,255,.1)",borderRadius:14,padding:16}}><small style={{opacity:.55}}>{name}</small><strong style={{display:"block",fontSize:24,margin:"7px 0 4px"}}>{value}</strong>{note&&<small style={{opacity:.45}}>{note}</small>}</article>}
function Section({title,children}:{title:string;children:ReactNode}){return <section style={{marginTop:22}}><h2 style={{fontSize:13,letterSpacing:".1em",textTransform:"uppercase",opacity:.75}}>{title}</h2>{children}</section>}
function ErrorBox({title,error,retry}:{title:string;error?:string;retry:()=>void}){return <div style={{padding:16,border:"1px solid rgba(255,180,80,.25)",borderRadius:12,marginTop:12}}><strong>{title} unavailable</strong><p style={{opacity:.6}}>{error??"No result was returned. Iris will not fabricate a value."}</p><button style={button} onClick={retry}>Retry</button></div>}
function Tree({value,depth=0}:{value:unknown;depth?:number}):ReactNode{if(value==null)return <span style={{opacity:.4}}>Not observed</span>;if(typeof value!=="object")return <span>{String(value)}</span>;const hidden=(k:string)=>/access.?token|refresh.?token|secret|api.?key|password|authorization/i.test(k);const entries=Array.isArray(value)?value.map((v,i)=>[String(i),v] as const):Object.entries(value as R);return <div style={{display:"grid",gap:4,marginLeft:depth?10:0}}>{entries.map(([k,v])=>hidden(k)?null:v!==null&&typeof v==="object"?<details key={k} open={depth<1} style={{paddingLeft:9}}><summary>{label(k)}</summary><Tree value={v} depth={depth+1}/></details>:<div key={k} style={{display:"grid",gridTemplateColumns:"minmax(140px,.7fr) minmax(180px,1.3fr)",gap:8,padding:"5px 0"}}><span style={{opacity:.5}}>{label(k)}</span><Tree value={v} depth={depth+1}/></div>)}</div>}
function Overview({o,i,setPage}:{o:R;i:R|null;setPage:(p:Page)=>void}){return <><Section title="Observed account state"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><Metric name="Accounts" value={o.accounts?.length??0}/><Metric name="Recent transactions" value={o.recent_transactions?.length??0}/><Metric name="Liquid position" value={money(i?.net_worth?.liquid_assets)} note={i?"Calculated from evidence":"Intelligence still loading"}/><Metric name="Cash flow" value={money(i?.cash_flow?.net)} note={i?"Calculated from evidence":"Intelligence still loading"}/></div></Section><Section title="Recent canonical observations"><div style={{display:"grid",gap:6}}>{(o.recent_transactions??[]).slice(0,12).map((t:R)=><div key={t.id} style={row}><span>{t.merchant_name??t.name??"Transaction"}<small style={{display:"block",opacity:.45}}>{t.posted_date??"—"} · {t.transaction_class??"unclassified"}</small></span><strong>{money(t.amount)}</strong></div>)}</div></Section><Section title="Iris status"><div style={row}><span>{i?"Intelligence loaded and evidence-bounded.":"Canonical account data is available; intelligence is loading independently."}</span><button style={button} onClick={()=>setPage(i?"intelligence":"overview")}>{i?"Inspect intelligence":"Refresh"}</button></div></Section></>}
function Money({o,i}:{o:R;i:R|null}){return <><Section title="Accounts"><div style={{display:"grid",gap:7}}>{(o.accounts??[]).map((a:R)=><div key={a.id} style={row}><span><strong>{a.name??"Account"}</strong><small style={{display:"block",opacity:.45}}>{label(a.subtype??a.type??"account")}{a.mask?` · ••••${a.mask}`:""}</small></span><strong>{money(a.current_balance??a.available_balance)}</strong></div>)}</div></Section><Section title="Derived financial state"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><Metric name="Liquid assets" value={money(i?.net_worth?.liquid_assets)}/><Metric name="Revolving debt" value={money(i?.debt_health?.revolvingDebt)}/><Metric name="Credit utilization" value={i?.debt_health?.creditUtilization==null?"—":`${(i.debt_health.creditUtilization*100).toFixed(1)}%`}/></div></Section></>}
function Intelligence({i}:{i:R}){return <><Section title="Iris — supreme intelligence"><div style={row}><span>{i.narrative??"Evidence-bounded intelligence is available."}</span><small>Governed</small></div></Section><Section title="Core intelligence"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><Metric name="Evidence gate" value={i.intelligence_gate?.ready?"Ready":"Constrained"}/><Metric name="Composition" value={i.intelligence_composition?.generated??i.intelligence_composition?.paths??"Available"}/><Metric name="Source fidelity" value={i.source_fidelity?.status??"Limited"}/><Metric name="Provider lineage" value={i.provider_lineage?.lineageComplete?"Complete":"Limited"}/></div></Section><Section title="Intelligence graph"><details open style={{padding:14,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><summary>Observed graph and derived results</summary><Tree value={{intelligence_graph:i.intelligence_graph,evidence_graph:i.evidence_graph,uncertainty:i.uncertainty,validation:i.validation}}/></details></Section></>}
function Data({source}:{source:R}){return <><Section title="Supabase canonical source of truth"><p style={{opacity:.6}}>This is authenticated read-only evidence. Protected credentials are withheld. Every displayed financial value must reconcile to canonical Supabase data or a declared deterministic calculation.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:10}}><Metric name="Accounts" value={source.counts?.accounts??0}/><Metric name="Transactions" value={source.counts?.transactions??0}/><Metric name="Transaction observations" value={source.counts?.transaction_observations??0}/><Metric name="Calculations" value={source.counts?.calculations??0}/></div></Section><Section title="Complete available evidence"><details open style={{padding:14,border:"1px solid rgba(255,255,255,.08)",borderRadius:12}}><summary>Canonical + provenance + audit</summary><Tree value={source}/></details></Section></>}
function Evidence({source,i}:{source:R|null;i:R|null}){return <><Section title="Evidence state"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><Metric name="Canonical source" value="Supabase"/><Metric name="Source fidelity" value={i?.source_fidelity?.status??"Pending"}/><Metric name="Provider lineage" value={i?.provider_lineage?.lineageComplete?"Complete":"Pending / limited"}/></div></Section><Section title="Reverse lineage"><Tree value={source?.lineage??i?.evidence_graph??null}/></Section></>}

export function IrisWorkspaceV3(){const[page,setPage]=useState<Page>("overview");const[o,setO]=useState<R|null>(null);const[i,setI]=useState<R|null>(null);const[source,setSource]=useState<R|null>(null);const[overviewError,setOverviewError]=useState<string>();const[intelligenceError,setIntelligenceError]=useState<string>();const[sourceError,setSourceError]=useState<string>();const[loadingOverview,setLoadingOverview]=useState(true);const[loadingIntelligence,setLoadingIntelligence]=useState(false);const[loadingSource,setLoadingSource]=useState(false);
 const loadOverview=useCallback(async()=>{setLoadingOverview(true);setOverviewError(undefined);try{setO(await api.getOverview())}catch(e){setOverviewError(e instanceof Error?e.message:"Unable to load account state")}finally{setLoadingOverview(false)}},[]);
 const loadIntelligence=useCallback(async()=>{if(!o?.accounts?.length)return;setLoadingIntelligence(true);setIntelligenceError(undefined);try{setI(await api.getIntelligence())}catch(e){setIntelligenceError(e instanceof Error?e.message:"Unable to load intelligence")}finally{setLoadingIntelligence(false)}},[o]);
 const loadSource=useCallback(async()=>{setLoadingSource(true);setSourceError(undefined);try{setSource(await api.getSourceTruth(200))}catch(e){setSourceError(e instanceof Error?e.message:"Unable to load source evidence")}finally{setLoadingSource(false)}},[]);
 useEffect(()=>{void loadOverview()},[loadOverview]);useEffect(()=>{if(o?.accounts?.length){void loadIntelligence();void loadSource()}},[o,loadIntelligence,loadSource]);
 if(loadingOverview&&!o)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#07090e",color:"white"}}><div><strong>Iris</strong><p style={{opacity:.6}}>Reading canonical account state…</p></div></div>;
 if(!o)return <div style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"#07090e",color:"white"}}><div><strong>Iris could not read account state.</strong><ErrorBox title="Account state" error={overviewError} retry={()=>void loadOverview()}/></div></div>;
 if(!o.accounts?.length)return <div style={{minHeight:"100vh",background:"#07090e",color:"white",display:"grid",placeItems:"center"}}><div style={{textAlign:"center",maxWidth:620}}><h1>Connect your financial accounts.</h1><p style={{opacity:.6}}>Plaid Link is only the authorized connection mechanism. Supabase is the canonical source of truth.</p><PlaidLinkButton onSuccess={()=>void loadOverview()}/></div></div>;
 let body:ReactNode;if(page==="overview")body=<Overview o={o} i={i} setPage={setPage}/>;else if(page==="money")body=<Money o={o} i={i}/>;else if(page==="activity")body=<Section title="Canonical activity"><div style={{display:"grid",gap:6}}>{(o.recent_transactions??[]).map((t:R)=><div key={t.id} style={row}><span>{t.merchant_name??t.name??"Transaction"}</span><strong>{money(t.amount)}</strong></div>)}</div></Section>;else if(page==="intelligence")body=loadingIntelligence&&!i?<p style={{opacity:.5}}>Loading intelligence independently…</p>:i?<Intelligence i={i}/>:<ErrorBox title="Intelligence" error={intelligenceError} retry={()=>void loadIntelligence()}/>;else if(page==="data")body=loadingSource&&!source?<p style={{opacity:.5}}>Loading Supabase evidence independently…</p>:source?<Data source={source}/>:<ErrorBox title="Source evidence" error={sourceError} retry={()=>void loadSource()}/>;else if(page==="evidence")body=(source||i)?<Evidence source={source} i={i}/>:<ErrorBox title="Evidence" error={sourceError??intelligenceError} retry={()=>{void loadSource();void loadIntelligence()}}/>;else if(page==="cashflow")body=i?<Section title="Cash flow"><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><Metric name="Inflows" value={money(i.cash_flow?.inflow)}/><Metric name="Outflows" value={money(i.cash_flow?.outflow)}/><Metric name="Net" value={money(i.cash_flow?.net)}/><Metric name="Safe to spend" value={money(i.cash_flow_safety?.safeToSpend)}/></div></Section>:<ErrorBox title="Intelligence" error={intelligenceError??"Still loading"} retry={()=>void loadIntelligence()}/>;else body=i?<Section title="Spending"><Tree value={{spending_by_domain:i.spending_by_domain,category_drift:i.category_drift,anomalies:i.anomalies}}/></Section>:<ErrorBox title="Intelligence" error={intelligenceError??"Still loading"} retry={()=>void loadIntelligence()}/>;
 return <div style={{minHeight:"100vh",background:"#07090e",color:"white",fontFamily:"Inter,system-ui,sans-serif"}}><aside style={{position:"fixed",inset:"0 auto 0 0",width:210,padding:20,borderRight:"1px solid rgba(255,255,255,.07)",background:"#07090e"}}><button style={{...button,width:"100%",textAlign:"left",marginBottom:18}} onClick={()=>setPage("overview")}><strong>iBag</strong><small style={{display:"block",opacity:.5}}>Financial intelligence by Iris</small></button><nav style={{display:"grid",gap:5}}>{pages.map(p=><button key={p} style={{...button,textAlign:"left",background:page===p?"rgba(255,255,255,.09)":"rgba(255,255,255,.045)"}} onClick={()=>setPage(p)}>{label(p)}</button>)}</nav><small style={{display:"block",marginTop:18,opacity:.4}}>Supabase = canonical source<br/>Plaid = connection / ingestion</small></aside><main style={{marginLeft:250,padding:"34px 30px",maxWidth:1200}}><header style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><small style={{opacity:.45,letterSpacing:".14em"}}>IRIS</small><h1 style={{margin:"5px 0 0"}}>{label(page)}</h1></div><button style={button} onClick={()=>void loadOverview()}>Refresh</button></header>{body}</main></div>;
}
