import { useEffect, useMemo, useState, type ReactNode } from "react";
import { api } from "../api/backend";
import "./IrisCommandSurface.css";

type Props={page?:string;go?:(page:string)=>void};
const tiers=[["iris","01","Command","What Iris sees now, prioritized."],["iris/state","02","Financial State","Liquidity, debt, accounts and current position."],["iris/cash-flow","03","Cash Flow","Inflows, outflows, safety and forward pressure."],["iris/spending","04","Spending","Domains, categories, changes and anomalies."],["iris/roundups","05","Round-Ups","Round-Up opportunity and evidence-bounded calculation."],["iris/evidence","06","Evidence","Provider lineage, fidelity, boundaries and uncertainty."],["iris/intelligence","07","Intelligence","Analytical intelligence operating on observed evidence."],["iris/behavior","08","Behavior","Patterns, recurrence, drift and temporal signals."],["iris/reasoning","09","Reasoning","Relationships, causes and investigations."],["iris/decisions","10","Decisions","Alternatives, consequences, goals and optimization."],["iris/simulation","11","Simulation","Scenarios and counterfactual calculations."],["iris/maximum","12","Maximum Intelligence","Synthesis, validation, learning and adaptation."]] as const;
const label=(s:any)=>String(s??"—").replaceAll("_"," ").replaceAll("-"," ").replace(/\b\w/g,c=>c.toUpperCase());
const money=(n:any)=>{const v=Number(n);return n==null||!Number.isFinite(v)?"—":`${v<0?"−":""}$${Math.abs(v).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`};
const evidenceLabel=(v:any)=>({observed:"Observed",calculated:"Calculated",inferred:"Iris inference",limited:"Limited evidence",insufficient_evidence:"Insufficient evidence"} as any)[v]??label(v);
const secretKey=(k:string)=>/access.?token|secret|api.?key|client.?secret|password|authorization/i.test(k);
function Evidence({value}:{value?:string}){const v=value??"insufficient_evidence";return <span className={`iris4-evidence ${v}`}>{evidenceLabel(v)}</span>}
function Value({value}:{value:any}){if(value==null)return <span>—</span>;if(typeof value==="number")return <span>{Number.isFinite(value)?value.toLocaleString("en-US",{maximumFractionDigits:6}):"—"}</span>;if(typeof value==="boolean")return <span>{value?"true":"false"}</span>;if(typeof value==="string")return <span>{value}</span>;return <span>{Array.isArray(value)?`${value.length} records`:`${Object.keys(value).length} fields`}</span>}
function Tree({value,path="root",depth=0}:{value:any;path?:string;depth?:number}):ReactNode{if(value==null||typeof value!=="object")return <Value value={value}/>;const entries=Array.isArray(value)?value.map((v,i)=>[String(i),v] as const):Object.entries(value);return <div className="iris4-tree">{entries.map(([key,v])=>{if(secretKey(key))return null;const p=`${path}.${key}`,complex=v!==null&&typeof v==="object";return complex?<details key={p} open={depth<1} className="iris4-tree-node"><summary><span>{label(key)}</span><small>{Array.isArray(v)?`${v.length} records`:`${Object.keys(v).length} fields`}</small></summary><div className="iris4-tree-child"><Tree value={v} path={p} depth={depth+1}/></div></details>:<div key={p} className="iris4-tree-leaf"><span>{label(key)}</span><Value value={v}/></div>})}</div>}
function Section({title,count,children}:{title:string;count?:any;children:ReactNode}){return <section className="iris-surface"><div className="iris-section-head"><span>{title}</span>{count!=null&&<b>{count}</b>}</div>{children}</section>}
function Snapshot({name,value}:{name:string;value:any}){return <details className="iris4-snapshot" open={name==="overview"}><summary><strong>{label(name)}</strong><small>{value==null?"—":Array.isArray(value)?`${value.length} records`:typeof value==="object"?`${Object.keys(value).length} fields`:"value"}</small></summary><Tree value={value} path={name}/></details>}
function SourceSurface({surface,overview}:{surface:any;overview:any}){const products=surface?.products??[];const items=surface?.items??[];return <Section title="PLAID SOURCE DATA · PRESERVED AS RECEIVED" count={products.length}><p className="iris4-note">The source layer remains separate from Iris interpretation. Every returned non-secret field is available through the hierarchy below; nothing is reduced to a metric-only summary.</p><div className="iris4-source-grid"><Snapshot name="accounts" value={overview?.accounts??[]}/><Snapshot name="transactions" value={overview?.recent_transactions??[]}/><Snapshot name="plaid_items" value={items}/><Snapshot name="plaid_products" value={products}/><Snapshot name="provider_evidence" value={surface?.provider_evidence??[]}/><Snapshot name="field_inventory" value={surface?.field_inventory??{}}/><Snapshot name="evidence_field_inventory" value={surface?.evidence_field_inventory??{}}/></div></Section>}
function IntelligenceSurface({intel}:{intel:any}){if(!intel)return null;return <Section title="IRIS INTELLIGENCE · COMPLETE RETURNED PAYLOAD"><p className="iris4-note">This is the complete hierarchical intelligence payload returned for the authenticated user. Arrays are not sliced for presentation. Evidence states remain attached to their data.</p><Snapshot name="intelligence" value={intel}/></Section>}
function TierFocus({page,intel,overview}:{page:string;intel:any;overview:any}){const map:any={"iris/state":["Financial State",["net_worth","debt_health","financial_state","accounts"]],"iris/cash-flow":["Cash Flow",["cash_flow","cash_flow_safety","forward_projection","layer_temporal"]],"iris/spending":["Spending",["spending_by_domain","spending_hierarchy","category_drift","anomalies","layer_behavioral"]],"iris/roundups":["Round-Ups",["roundup_projection"]],"iris/evidence":["Evidence",["evidence_boundary","source_fidelity","provider_lineage","evidence_graph","uncertainty","validation","plaid_iris_field_map"]],"iris/intelligence":["Intelligence",["intelligence_atlas","intelligence_composition","layer_composition","plaid_iris_field_map"]],"iris/behavior":["Behavior",["layer_behavioral","layer_temporal","anomalies","category_drift"]],"iris/reasoning":["Reasoning",["layer_reasoning","causal_analysis","intelligence_graph","investigations"]],"iris/decisions":["Decisions",["decision_graph","decision_intelligence","consequence_model","optimization_intelligence","goal_intelligence"]],"iris/simulation":["Simulation",["counterfactual_intelligence"]],"iris/maximum":["Maximum Intelligence",["layer_max_intelligence","higher_order_synthesis","adversarial_reasoning","meta_intelligence","iris_governor","iris_feature_registry"]]};const d=map[page];if(!d)return <Section title="COMMAND · OBSERVED + INTELLIGENCE"><CommandFacts intel={intel} overview={overview}/></Section>;return <Section title={`TIER ${tiers.find(t=>t[0]===page)?.[1]??""} · ${d[0]}`} count={d[1].length}><p className="iris4-note">All available fields for this tier are exposed below. Use each disclosure to inspect nested records instead of losing them to a flat summary.</p>{d[1].map((k:string)=><Snapshot key={k} name={k} value={intel?.[k]}/>)}</Section>}
function CommandFacts({intel,overview}:{intel:any;overview:any}){const cards=[["Accounts",overview?.accounts?.length,"observed"],["Transactions",overview?.recent_transactions?.length,"observed"],["Liquid position",intel?.net_worth?.liquid_assets,"calculated"],["Cash flow",intel?.cash_flow?.net,"calculated"],["Safe to spend",intel?.cash_flow_safety?.safeToSpend,"calculated"],["Round-Up opportunity",intel?.roundup_projection?.total,"calculated"]];return <div className="iris-metric-grid">{cards.map(([a,v,e])=><article className="iris-surface-card" key={String(a)}><span>{a}</span><strong>{typeof v==="number"&&String(a)!=="Accounts"&&String(a)!=="Transactions"?money(v):v??"—"}</strong><Evidence value={e}/></article>)}</div>}
export function IrisCommandSurface({page="iris",go}:Props){const[intel,setIntel]=useState<any>(null),[overview,setOverview]=useState<any>(null),[surface,setSurface]=useState<any>(null),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true);useEffect(()=>{let live=true;(async()=>{try{const[o,s]=await Promise.all([api.getOverview(),api.getPlaidSurface()]);if(!live)return;setOverview(o);setSurface(s);if(o?.accounts?.length){const i=await api.getIntelligence();if(live)setIntel(i)}}catch(e){if(live)setError(e instanceof Error?e.message:"Unable to load live financial data")}finally{if(live)setLoading(false)}})();return()=>{live=false}},[]);if(loading)return <main className="iris4-screen"><div className="iris4-empty"><span>IRIS</span><strong>Reading live source and intelligence data…</strong><p>Loading the complete observed boundary before presenting analysis.</p></div></main>;if(error&&!intel)return <main className="iris4-screen"><div className="iris4-empty"><strong>Live intelligence is unavailable.</strong><p>{error}</p><button onClick={()=>window.location.hash="workspace/plaid"}>Open Plaid source control →</button></div></main>;const tier=tiers.find(t=>t[0]===page)||tiers[0];return <main className="iris4-screen"><header className="iris4-hero"><div><span>IRIS · TIER {tier[1]}</span><h1>{tier[2]}</h1><p>{tier[3]}</p></div><div className="iris4-status"><b>Global evidence</b> {intel?.intelligence_gate?.status??"constrained"}<i/><b>Source records</b> {surface?.items?.length??0} items · {surface?.products?.length??0} product views<i/><b>Updated</b> {intel?.generated_at?new Date(intel.generated_at).toLocaleTimeString():"—"}</div></header><div className="iris4-layout"><nav className="iris4-nav">{tiers.map(t=><button key={t[0]} className={tier[0]===t[0]?"active":""} onClick={()=>go?.(t[0])}><small>{t[1]}</small><strong>{t[2]}</strong><span>{t[3]}</span></button>)}</nav><section className="iris4-body"><TierFocus page={page} intel={intel} overview={overview}/>{page==="iris"&&<SourceSurface surface={surface} overview={overview}/>}<IntelligenceSurface intel={intel}/></section></div></main>}
