import { useEffect, useState } from "react";
import { supabase } from "../api/supabase";

export function PlaidKnowledgeCenter(){
 const [rows,setRows]=useState<any[]>([]); const [q,setQ]=useState(""); const [open,setOpen]=useState<string|null>(null);
 useEffect(()=>{(async()=>{const {data}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_BACKEND_URL}/dashboard/plaid/knowledge`,{headers:{Authorization:`Bearer ${data.session?.access_token??""}`}});if(r.ok)setRows((await r.json()).records??[]);})();},[]);
 const filtered=rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase()));
 return <main style={{padding:32,fontFamily:"Inter,system-ui,sans-serif",background:"#f4f6f8",minHeight:"100vh",color:"#101828"}}><header><small>PLAID · PUBLIC KNOWLEDGE · IRIS</small><h1>Everything Iris can responsibly know about Plaid.</h1><p>Read-only educational reference. Public product knowledge is separate from real user financial evidence.</p><a href="/">← Back to Iris</a></header><section style={{background:"white",padding:18,borderRadius:14,margin:"20px 0"}}><b>Evidence boundary:</b> product existence, availability, consent or Item state does not prove that a user's financial data was observed.<br/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search every Plaid product and service…" style={{marginTop:14,padding:11,width:"100%",maxWidth:600}}/></section><section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:12}}>{filtered.map(r=><article key={r.id} style={{background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:16}}><button onClick={()=>setOpen(open===r.id?null:r.id)} style={{border:0,background:"none",padding:0,textAlign:"left",width:"100%",cursor:"pointer"}}><small>{r.kind} · {r.category}</small><h2>{r.name}</h2><p>{r.description}</p><small>{open===r.id?"Hide details ↑":"Open full mapping ↓"}</small></button>{open===r.id&&<div style={{marginTop:14,lineHeight:1.55}}><p><b>What:</b> {r.what_it_does}</p><p><b>How:</b> {r.how_it_works}</p><p><b>Who:</b> {r.who_uses_it}</p><p><b>When:</b> {r.when_used}</p><p><b>Why:</b> {r.why_it_exists}</p><p><b>Public data scope:</b> {r.public_data_scope}</p><p><b>Iris capabilities:</b> {(r.iris_capabilities??[]).join(", ")||"Not mapped"}</p><p><b>Plaid Item states:</b> {(r.plaid_item_states??[]).join(", ")||"Not an Item state"}</p><p><b>Availability:</b> {r.availability_notes}</p><p><b>Commercial:</b> {r.pricing_notes}</p><a href={r.official_source_url} target="_blank" rel="noreferrer">Official Plaid source</a>{r.official_docs_url&&<> · <a href={r.official_docs_url} target="_blank" rel="noreferrer">Official docs</a></>}</div>}</article>)}</section></main>;
}
