import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import { supabase } from "../api/supabase";
import { PlaidLinkButton } from "./PlaidLink";

type Knowledge = { id:string; key:string; name:string; kind:string; category?:string; description?:string; what_it_does?:string; how_it_works?:string; who_uses_it?:string; when_used?:string; why_it_exists?:string; public_data_scope?:string; iris_capabilities?:string[]; plaid_item_states?:string[]; availability_notes?:string; pricing_notes?:string; official_source_url?:string; official_docs_url?:string; verified_at?:string };

export function PlaidControlPlane(){
 const [rows,setRows]=useState<Knowledge[]>([]); const [runtime,setRuntime]=useState<any>(null); const [q,setQ]=useState(""); const [open,setOpen]=useState<string|null>(null); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [mode,setMode]=useState<"overview"|"knowledge"|"runtime">("overview");
 const load=async()=>{setLoading(true);try{const {data}=await supabase.auth.getSession();const r=await fetch(`${import.meta.env.VITE_BACKEND_URL}/dashboard/plaid/knowledge`,{headers:{Authorization:`Bearer ${data.session?.access_token??""}`}});if(!r.ok)throw new Error("Plaid knowledge request failed");const [k,s]=await Promise.all([r.json(),api.getPlaidSurface()]);setRows(k.records??[]);setRuntime(s);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load Plaid dashboard");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>rows.filter(r=>!q||JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const products=runtime?.products??[]; const active=products.filter((p:any)=>p.status==="active").length; const available=products.filter((p:any)=>p.status==="available").length; const observed=products.filter((p:any)=>p.status==="observed").length; const items=runtime?.items??[];
 if(loading)return <main className="plaid-space"><div className="plaid-loader"><i/><b>PLAID / IRIS</b><span>Synchronizing the intelligence surface…</span></div></main>;
 if(error)return <main className="plaid-space"><div className="plaid-error"><b>PLAID / IRIS</b><h1>Surface unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry connection</button></div></main>;
 return <main className="plaid-space">
  <header className="plaid-command"><div className="plaid-brand"><span className="plaid-orbit"/><div><small>PLAID · IRIS</small><strong>COMMAND SURFACE</strong></div></div><div className="plaid-command-right"><span className="live-dot">LIVE SURFACE</span><a href="/">IRIS ↗</a><PlaidLinkButton onSuccess={()=>void load()}/></div></header>
  <section className="plaid-hero"><div><span className="eyebrow">UNIFIED PLAID ENVIRONMENT</span><h1>Everything Iris knows.<br/><em>Nothing it invents.</em></h1><p>Public Plaid knowledge, live Item state and observed provider evidence converge here — separated by evidence so intelligence remains trustworthy.</p></div><div className="plaid-signal"><span>INTEGRITY</span><strong>Evidence<br/>gated</strong><small>Capability ≠ observation</small></div></section>
  <nav className="plaid-tabs"><button className={mode==="overview"?"active":""} onClick={()=>setMode("overview")}>Overview</button><button className={mode==="runtime"?"active":""} onClick={()=>setMode("runtime")}>Live runtime</button><button className={mode==="knowledge"?"active":""} onClick={()=>setMode("knowledge")}>Plaid knowledge</button></nav>
  {mode==="overview"&&<>
   <section className="plaid-grid plaid-overview"><div className="plaid-panel plaid-primary"><span className="eyebrow">PROVIDER NETWORK</span><strong>{items.length}</strong><h2>Connected Items</h2><p>Actual Plaid connections available to this account.</p><div className="rings"><i/><i/><i/></div></div><Metric label="Knowledge mapped" value={rows.length}/><Metric label="Active capabilities" value={active}/><Metric label="Available" value={available}/><Metric label="Observed" value={observed}/></section>
   <section className="plaid-grid plaid-lower"><div className="plaid-panel wide"><div className="panel-title"><div><span className="eyebrow">LIVE PROVIDER STATE</span><h2>Connected institutions</h2></div><button onClick={()=>setMode("runtime")}>Explore →</button></div>{items.length===0?<Empty text="No connected institution is currently available to display."/>:items.slice(0,3).map((i:any)=><RuntimeRow key={i.plaid_item_id} item={i}/>)}</div><div className="plaid-panel"><span className="eyebrow">IRIS REFERENCE</span><h2>Public intelligence</h2><p>{rows.length} mapped Plaid capabilities are available to Iris for educational and product-understanding questions.</p><div className="knowledge-preview">{rows.slice(0,5).map(r=><button key={r.id} onClick={()=>{setMode("knowledge");setOpen(r.id)}}><span>{r.kind}</span><b>{r.name}</b><i>→</i></button>)}</div></div></section>
  </>}
  {mode==="runtime"&&<section className="plaid-panel full"><div className="panel-title"><div><span className="eyebrow">RUNTIME / USER DATA</span><h2>Provider state</h2><p>Runtime state is not the same thing as observed financial data.</p></div><button onClick={()=>void load()}>↻ Refresh</button></div>{items.length===0?<Empty text="No connected Items."/>:items.map((i:any)=><RuntimeRow key={i.plaid_item_id} item={i} detailed/>)}<div className="evidence-rail"><b>OBSERVATION BOUNDARY</b><span>Observed → Calculated → Pattern → Inference</span><small>Unavailable, unconsented, expired or unsupported data remains explicitly bounded.</small></div></section>}
  {mode==="knowledge"&&<section className="plaid-panel full"><div className="panel-title"><div><span className="eyebrow">PUBLIC / OFFICIAL / READ-ONLY</span><h2>Plaid knowledge graph</h2><p>Capabilities and documentation Iris can explain without treating them as evidence of a user's data.</p></div><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search Plaid…"/></div><div className="knowledge-grid">{filtered.map(r=><article className={open===r.id?"knowledge-card open":"knowledge-card"} key={r.id}><button className="knowledge-head" onClick={()=>setOpen(open===r.id?null:r.id)}><span>{r.kind} · {r.category??"Plaid"}</span><b>{r.name}</b><small>{r.description}</small><i>{open===r.id?"−":"+"}</i></button>{open===r.id&&<div className="knowledge-detail"><Fact label="What" value={r.what_it_does}/><Fact label="How" value={r.how_it_works}/><Fact label="Who" value={r.who_uses_it}/><Fact label="When" value={r.when_used}/><Fact label="Why" value={r.why_it_exists}/><Fact label="Public scope" value={r.public_data_scope}/><Fact label="Iris mapping" value={(r.iris_capabilities??[]).join(", ")||"Reference knowledge"}/><Fact label="Item states" value={(r.plaid_item_states??[]).join(", ")||"Not an Item product state"}/><Fact label="Availability" value={r.availability_notes}/><Fact label="Commercial" value={r.pricing_notes}/><div className="source-links">{r.official_source_url&&<a href={r.official_source_url} target="_blank" rel="noreferrer">Official source ↗</a>}{r.official_docs_url&&<a href={r.official_docs_url} target="_blank" rel="noreferrer">Official docs ↗</a>}</div></div>}</article>)}</div></section>}
 </main>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="plaid-panel plaid-metric"><span>{label}</span><strong>{value}</strong><small>live index</small></div>}
function RuntimeRow({item,detailed}:{item:any;detailed?:boolean}){return <div className="runtime-row"><div className="institution-mark">{(item.institution_name??"P").slice(0,1).toUpperCase()}</div><div className="runtime-name"><b>{item.institution_name??"Institution"}</b><span>{item.status??"unknown"} · {item.last_synced_at?new Date(item.last_synced_at).toLocaleString():"sync not recorded"}</span></div><div className="runtime-state"><i/>{item.status??"unknown"}</div>{detailed&&<div className="runtime-products"><span>Active / billed</span><b>{item.billed_products?.length?item.billed_products.join(" · "):"None reported"}</b><span>Consented</span><b>{item.consented_products?.length?item.consented_products.join(" · "):"None reported"}</b><span>Available</span><b>{item.available_products?.length?item.available_products.join(" · "):"None reported"}</b></div>}</div>}
function Empty({text}:{text:string}){return <div className="plaid-empty"><span>◌</span>{text}</div>}
function Fact({label,value}:{label:string;value?:string}){return <div className="fact"><span>{label}</span><p>{value||"—"}</p></div>}
const styles=`plaid-space{}`;
