import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import { supabase } from "../api/supabase";
import { PlaidLinkButton } from "./PlaidLink";
import { PlaidEvidenceUpgradeButton } from "./PlaidEvidenceUpgradeButton";
import "./PlaidControlPlane.css";

type Product={key:string;displayName:string;status:string;observed?:boolean;item_count?:number;observed_item_count?:number;active_item_count?:number;consented_item_count?:number;available_item_count?:number};
type Item={item_id:string;institution_name?:string;status?:string;last_synced_at?:string;products?:Product[]};
type Evidence={id?:string;item_id?:string;product?:string;source_domain?:string;account_id?:string;plaid_transaction_id?:string;raw_response?:unknown;[key:string]:unknown};
type Knowledge={id:string;name:string;kind:string;category?:string;description?:string;what_it_does?:string;how_it_works?:string;who_uses_it?:string;when_used?:string;why_it_exists?:string;public_data_scope?:string;iris_capabilities?:string[];availability_notes?:string;pricing_notes?:string;official_source_url?:string;official_docs_url?:string};
const keys=["auth","transactions","balance","identity","assets","liabilities","investments","statements"];
const labels:Record<string,string>={observed:"Observed",active:"Active",consented:"Consented",available:"Available",not_available:"Not available",not_connected:"Not connected"};
const title=(s:string)=>s.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export function PlaidCommandSurface(){
 const [runtime,setRuntime]=useState<any>(null),[knowledge,setKnowledge]=useState<Knowledge[]>([]),[mode,setMode]=useState("overview"),[query,setQuery]=useState(""),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const [itemId,setItemId]=useState<string|null>(null),[productKey,setProductKey]=useState<string|null>(null),[evidenceId,setEvidenceId]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token??"";const [s,k]=await Promise.all([api.getPlaidSurface(),fetch(`${import.meta.env.VITE_BACKEND_URL}/dashboard/plaid/knowledge`,{headers:{Authorization:`Bearer ${token}`}})]);if(!k.ok)throw new Error("Plaid knowledge request failed");setRuntime(s);setKnowledge((await k.json()).records??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load Plaid source surface")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const items:Item[]=runtime?.items??[],products:Product[]=runtime?.products??[],evidence:Evidence[]=runtime?.provider_evidence??[];
 const complete=items.filter(i=>keys.every(k=>i.products?.some(p=>p.key===k&&p.status==="observed"))).length;
 const selectedItem=items.find(i=>i.item_id===itemId);
 const selectedProduct=products.find(p=>p.key===productKey);
 const selectedEvidence=evidence.find((e:any)=>String(e.id)===evidenceId);
 const filteredKnowledge=useMemo(()=>knowledge.filter(k=>!query||JSON.stringify(k).toLowerCase().includes(query.toLowerCase())),[knowledge,query]);
 const itemEvidence=useMemo(()=>itemId?evidence.filter(e=>e.item_id===itemId):[],[evidence,itemId]);
 const productEvidence=useMemo(()=>productKey?(itemId?itemEvidence:evidence).filter(e=>String(e.product??e.source_domain)===productKey):[],[evidence,itemEvidence,itemId,productKey]);
 const go=(next:string,{item=null,product=null,e=null}:{item?:string|null;product?:string|null;e?:string|null}={})=>{setMode(next);setItemId(item);setProductKey(product);setEvidenceId(e);window.scrollTo({top:0,behavior:"smooth"});};
 if(loading)return <main className="plaid-space"><div className="plaid-loader"><i/><b>PLAID / SOURCE CONTROL</b><span>Reading live provider state and evidence…</span></div></main>;
 if(error)return <main className="plaid-space"><div className="plaid-error"><b>PLAID / SOURCE CONTROL</b><h1>Surface unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry connection</button></div></main>;
 return <main className="plaid-space"><header className="plaid-command"><div className="plaid-brand"><span className="plaid-orbit"/><div><small>PLAID · SOURCE CONTROL</small><strong>PROVIDER COMMAND</strong></div></div><div className="plaid-command-right"><span className="live-dot">LIVE · READ ONLY</span><PlaidLinkButton onSuccess={()=>void load()}/></div></header>
  <section className="plaid-hero"><div><span className="eyebrow">CANONICAL 8-DOMAIN SURFACE</span><h1>Provider truth.<br/><em>Evidence before intelligence.</em></h1><p>Navigate from the provider connection to the exact product, observation, field and raw response. Capability is never silently treated as observed evidence.</p></div><div className="plaid-signal"><span>SAME-ITEM GATE</span><strong>{complete}/{items.length}</strong><small>Items with all eight observed</small></div></section>
  <nav className="plaid-tabs">{[["overview","Overview"],["items","Items"],["products","8 products"],["evidence","Evidence"],["knowledge","Knowledge"]].map(([id,text])=><button key={id} className={mode===id?"active":""} onClick={()=>go(id)}>{text}</button>)}</nav>
  {mode==="overview"&&<><section className="plaid-grid plaid-overview"><Big label="Connected Items" value={items.length} note="Authenticated provider connections"/><Big label="Observed domains" value={products.filter(p=>p.status==="observed").length} note="Current canonical evidence"/><Big label="Active" value={products.filter(p=>p.status==="active").length} note="Not observation"/><Big label="Available" value={products.filter(p=>p.status==="available").length} note="Not observation"/></section><section className="plaid-grid plaid-lower"><div className="plaid-panel wide"><Title eyebrow="LIVE PROVIDER STATE" title="Connected institutions" action="Open all Items" onClick={()=>go("items")}/>{items.length?items.map(i=><ItemRow key={i.item_id} item={i} onOpen={()=>go("item",{item:i.item_id})}/>):<Empty text="No connected Items."/>}</div><div className="plaid-panel"><Title eyebrow="EVIDENCE COVERAGE" title="Canonical domains"/><div className="product-mini-grid">{products.map(p=><button key={p.key} className="drill-card" onClick={()=>go("product",{product:p.key})}><span>{p.displayName}</span><b className={`state ${p.status}`}>{labels[p.status]??p.status}</b><small>Open product →</small></button>)}</div></div></section></>}
  {mode==="items"&&<section className="plaid-panel full"><Title eyebrow="LEVEL 1 · PROVIDER ITEMS" title="Connected Items" action="Back to overview" onClick={()=>go("overview")}/><p className="drill-intro">Choose an Item to inspect its eight canonical domains. Each Item is an independent evidence boundary.</p>{items.length?items.map(i=><ItemRow key={i.item_id} item={i} detailed onOpen={()=>go("item",{item:i.item_id})} refresh={()=>void load()}/>):<Empty text="No connected Items."/>}</section>}
  {mode==="item"&&selectedItem&&<ItemDetail item={selectedItem} evidence={itemEvidence} onBack={()=>go("items")} onProduct={(p)=>go("product",{item:selectedItem.item_id,product:p})} onEvidence={(id,p)=>go("observation",{item:selectedItem.item_id,product:p,e:id})}/>} 
  {mode==="products"&&<section className="plaid-panel full"><Title eyebrow="LEVEL 1 · CANONICAL PRODUCTS" title="All eight Plaid domains" action="Back to overview" onClick={()=>go("overview")}/><p className="drill-intro">Choose a product to descend into Item state, observed provider records, nested fields and raw responses.</p><div className="product-table">{products.map(p=><article className="product-row" key={p.key}><div><strong>{p.displayName}</strong><span>{p.key}</span></div><b className={`state state-large ${p.status}`}>{labels[p.status]??p.status}</b><div><small>Items</small><b>{p.item_count??0}</b></div><div><small>Observed</small><b>{p.observed_item_count??0}</b></div><div><small>Active</small><b>{p.active_item_count??0}</b></div><button className="drill-button" onClick={()=>go("product",{product:p.key})}>Open {p.displayName} →</button></article>)}</div></section>}
  {mode==="product"&&selectedProduct&&<ProductDetail product={selectedProduct} items={items} evidence={productEvidence} itemId={itemId} onBack={()=>itemId?go("item",{item:itemId}):go("products")} onItem={(id)=>go("product",{item:id,product:selectedProduct.key})} onEvidence={(id)=>go("observation",{item:itemId,product:selectedProduct.key,e:id})}/>} 
  {mode==="evidence"&&<EvidenceIndex evidence={evidence} items={items} onBack={()=>go("overview")} onProduct={(p)=>go("product",{product:p})} onItem={(id)=>go("item",{item:id})} onEvidence={(id,p,i)=>go("observation",{item:i,product:p,e:id})}/>} 
  {mode==="observation"&&selectedEvidence&&<ObservationDetail evidence={selectedEvidence} onBack={()=>productKey?go("product",{item:itemId,product:productKey}):go("evidence")} />}
  {mode==="knowledge"&&<section className="plaid-panel full"><Title eyebrow="PUBLIC / OFFICIAL / READ-ONLY" title="Plaid knowledge" action="Back to overview" onClick={()=>go("overview")}/><input className="plaid-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Plaid knowledge…"/><div className="knowledge-grid">{filteredKnowledge.map(k=><article className={open===k.id?"knowledge-card open":"knowledge-card"} key={k.id}><button className="knowledge-head" onClick={()=>setOpen(open===k.id?null:k.id)}><span>{k.kind} · {k.category??"Plaid"}</span><b>{k.name}</b><small>{k.description}</small><i>{open===k.id?"−":"+"}</i></button>{open===k.id&&<div className="knowledge-detail"><Fact label="What" value={k.what_it_does}/><Fact label="How" value={k.how_it_works}/><Fact label="Who" value={k.who_uses_it}/><Fact label="When" value={k.when_used}/><Fact label="Why" value={k.why_it_exists}/><Fact label="Public scope" value={k.public_data_scope}/><Fact label="Iris mapping" value={(k.iris_capabilities??[]).join(", ")||"Reference only"}/><Fact label="Availability" value={k.availability_notes}/><Fact label="Commercial" value={k.pricing_notes}/><div className="source-links">{k.official_source_url&&<a href={k.official_source_url} target="_blank" rel="noreferrer">Official source ↗</a>}{k.official_docs_url&&<a href={k.official_docs_url} target="_blank" rel="noreferrer">Official docs ↗</a>}</div></div>}</article>)}</div></section>}
 </main>;
}
function ItemDetail({item,evidence,onBack,onProduct,onEvidence}:{item:Item;evidence:Evidence[];onBack:()=>void;onProduct:(p:string)=>void;onEvidence:(id:string,p:string)=>void}){const observed=(item.products??[]).filter(p=>p.status==="observed");return <section className="plaid-panel full"><Crumbs parts={["Plaid","Items",item.institution_name??item.item_id]}/><Title eyebrow="LEVEL 2 · ITEM DETAIL" title={item.institution_name??"Provider Item"} action="← Items" onClick={onBack}/><div className="detail-meta"><Fact label="Item ID" value={item.item_id}/><Fact label="Provider status" value={item.status}/><Fact label="Last sync" value={item.last_synced_at?new Date(item.last_synced_at).toLocaleString():"—"}/><Fact label="Observed domains" value={`${observed.length}/8`}/></div><h3>Canonical products</h3><div className="drill-list">{(item.products??[]).map(p=><button key={p.key} className="drill-row" onClick={()=>onProduct(p.key)}><span><b>{p.displayName}</b><small>{p.key} · {labels[p.status]??p.status}</small></span><b className={`state ${p.status}`}>{labels[p.status]??p.status}</b><strong>Open →</strong></button>)}</div><h3>Observed records on this Item</h3>{evidence.length?evidence.slice(0,80).map((e:any,i)=><button key={String(e.id??i)} className="drill-row" onClick={()=>onEvidence(String(e.id??`${e.product}-${i}`),String(e.product??e.source_domain))}><span><b>{title(String(e.product??e.source_domain??"provider"))}</b><small>{e.account_id?`Account ${e.account_id}`:e.plaid_transaction_id?`Transaction ${e.plaid_transaction_id}`:"Provider observation"}</small></span><b>Observed</b><strong>Inspect →</strong></button>):<Empty text="No current observed provider records for this Item."/>}</section>}
function ProductDetail({product,items,evidence,itemId,onBack,onItem,onEvidence}:{product:Product;items:Item[];evidence:Evidence[];itemId:string|null;onBack:()=>void;onItem:(id:string)=>void;onEvidence:(id:string,p:string)=>void}){const relevant=items.filter(i=>!itemId||i.item_id===itemId);return <section className="plaid-panel full"><Crumbs parts={["Plaid","Products",product.displayName,...(itemId?[items.find(i=>i.item_id===itemId)?.institution_name??itemId]:[])]}/><Title eyebrow="LEVEL 2 · PRODUCT DETAIL" title={product.displayName} action="← Back" onClick={onBack}/><div className="detail-meta"><Fact label="Canonical key" value={product.key}/><Fact label="State" value={labels[product.status]??product.status}/><Fact label="Items" value={String(product.item_count??0)}/><Fact label="Observed Items" value={String(product.observed_item_count??0)}/></div><h3>Item-level state</h3><div className="drill-list">{relevant.map(i=>{const state=i.products?.find(p=>p.key===product.key);return <button key={i.item_id} className="drill-row" onClick={()=>onItem(i.item_id)}><span><b>{i.institution_name??i.item_id}</b><small>{i.item_id}</small></span><b className={`state ${state?.status??"not_available"}`}>{labels[state?.status??"not_available"]}</b><strong>Open Item →</strong></button>})}</div><h3>Observed provider records</h3>{evidence.length?evidence.slice(0,100).map((e:any,i)=><button key={String(e.id??i)} className="drill-row" onClick={()=>onEvidence(String(e.id??`${e.product}-${i}`),String(e.product??e.source_domain))}><span><b>{title(String(e.product??e.source_domain??"provider"))}</b><small>{e.plaid_transaction_id?`Transaction ${e.plaid_transaction_id}`:e.account_id?`Account ${e.account_id}`:`Record ${i+1}`}</small></span><b>Observed</b><strong>Inspect →</strong></button>):<Empty text="No current observed records for this product selection."/>}</section>}
function ObservationDetail({evidence,onBack}:{evidence:Evidence;onBack:()=>void}){const [raw,setRaw]=useState(false);const walk=(v:unknown,path="root",out:string[]=[]):string[]=>{if(v===null||typeof v!=="object"){out.push(`${path} = ${v===null?"null":String(v)}`);return out}if(Array.isArray(v)){out.push(`${path} = Array(${v.length})`);v.forEach((x,i)=>walk(x,`${path}[${i}]`,out));return out}for(const [k,x] of Object.entries(v as any))walk(x,`${path}.${k}`,out);return out};const fields=walk(evidence.raw_response);return <section className="plaid-panel full"><Crumbs parts={["Plaid","Evidence",title(String(evidence.product??evidence.source_domain??"Provider")),String(evidence.id??"")]}/><Title eyebrow="LEVEL 3 · EXACT OBSERVATION" title="Provider observation" action="← Back" onClick={onBack}/><div className="detail-meta">{Object.entries(evidence).filter(([k])=>k!=="raw_response").map(([k,v])=><Fact key={k} label={title(k)} value={typeof v==="object"?JSON.stringify(v):String(v??"null")}/>)}</div><div className="evidence-rail"><b>RAW SOURCE BOUNDARY</b><span>Observed → inspect exact response → no interpretation</span><small>This screen displays the provider observation itself. It does not convert optional fields into missing-data claims.</small></div><button className="drill-button" onClick={()=>setRaw(!raw)}>{raw?"Hide raw Plaid response":"Show exact raw Plaid response"}</button>{raw&&<pre className="raw-view">{JSON.stringify(evidence.raw_response,null,2)}</pre>}<h3>Exact returned field paths</h3><div className="field-path-list">{fields.filter(x=>!x.includes(" = [object Object]")).map((x,i)=><code key={i}>{x}</code>)}</div></section>}
function EvidenceIndex({evidence,items,onBack,onProduct,onItem,onEvidence}:{evidence:Evidence[];items:Item[];onBack:()=>void;onProduct:(p:string)=>void;onItem:(i:string)=>void;onEvidence:(id:string,p:string,i?:string)=>void}){const [q,setQ]=useState("");const products=[...new Set(evidence.map(e=>String(e.product??e.source_domain??"unknown")))].sort();const filtered=evidence.filter(e=>!q||JSON.stringify(e).toLowerCase().includes(q.toLowerCase()));return <section className="plaid-panel full"><Title eyebrow="LEVEL 1 · PROVIDER EVIDENCE" title="Evidence navigation" action="Back to overview" onClick={onBack}/><p className="drill-intro">This is the entry point into the evidence tree. Choose a domain, Item, or exact observation rather than reading one flat wall of records.</p><input className="plaid-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search raw fields and values…"/><div className="evidence-tree">{products.map(p=><article key={p} className="tree-node"><button className="drill-row" onClick={()=>onProduct(p)}><span><b>{title(p)}</b><small>{evidence.filter(e=>String(e.product??e.source_domain)===p).length} observed records</small></span><strong>Open domain →</strong></button><div className="tree-children">{items.filter(i=>filtered.some(e=>e.item_id===i.item_id&&String(e.product??e.source_domain)===p)).map(i=><button key={i.item_id} className="tree-leaf" onClick={()=>onItem(i.item_id)}><span>{i.institution_name??i.item_id}</span><small>Open Item →</small></button>)}</div></article>)}</div><h3>Matching exact observations ({filtered.length})</h3>{filtered.slice(0,100).map((e:any,i)=><button key={String(e.id??i)} className="drill-row" onClick={()=>onEvidence(String(e.id??`${e.product}-${i}`),String(e.product??e.source_domain),e.item_id)}><span><b>{title(String(e.product??e.source_domain??"provider"))}</b><small>{e.item_id?`Item ${e.item_id}`:"No Item ID"} · {e.plaid_transaction_id?`Transaction ${e.plaid_transaction_id}`:e.account_id?`Account ${e.account_id}`:"Provider observation"}</small></span><strong>Inspect exact record →</strong></button>)}</section>}
function Crumbs({parts}:{parts:string[]}){return <div className="plaid-breadcrumbs">{parts.filter(Boolean).map((p,i)=><span key={`${p}-${i}`}>{i?" / ":""}{p}</span>)}</div>}
function ItemRow({item,detailed,onOpen,refresh}:{item:Item;detailed?:boolean;onOpen:()=>void;refresh?:()=>void}){const ps=item.products??[],obs=ps.filter(p=>p.status==="observed").length;return <div className={`runtime-row ${detailed?"detailed":""}`}><div className="institution-mark">{(item.institution_name??"P")[0].toUpperCase()}</div><div className="runtime-name"><b>{item.institution_name??"Institution"}</b><span>{item.status??"unknown"} · {item.last_synced_at?new Date(item.last_synced_at).toLocaleString():"sync not recorded"}</span></div><div className="runtime-state"><i/>{obs}/8 observed</div><button className="drill-button" onClick={onOpen}>Open Item →</button>{detailed&&<div className="runtime-products">{ps.map(p=><button key={p.key} className="mini-drill" onClick={onOpen}><span>{p.displayName}</span><b className={`state ${p.status}`}>{labels[p.status]??p.status}</b></button>)}{refresh&&<PlaidEvidenceUpgradeButton itemId={item.item_id} observedProducts={ps.filter(p=>p.observed).map(p=>p.key)} onComplete={refresh}/>}</div>}</div>}
function Title({eyebrow,title,action,onClick}:{eyebrow:string;title:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Big({label,value,note}:{label:string;value:number;note:string}){return <div className="plaid-panel plaid-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function Fact({label,value}:{label:string;value?:string}){return <div className="fact"><span>{label}</span><p>{value||"—"}</p></div>}
function Empty({text}:{text:string}){return <div className="plaid-empty"><span>◌</span>{text}</div>}
