import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import { supabase } from "../api/supabase";
import { PlaidLinkButton } from "./PlaidLink";
import { PlaidEvidenceUpgradeButton } from "./PlaidEvidenceUpgradeButton";
import "./PlaidControlPlane.css";

type Product={key:string;displayName:string;status:string;observed?:boolean;item_count?:number;observed_item_count?:number;active_item_count?:number;consented_item_count?:number;available_item_count?:number};
type Item={item_id:string;institution_name?:string;status?:string;last_synced_at?:string;products?:Product[]};
type Knowledge={id:string;name:string;kind:string;category?:string;description?:string;what_it_does?:string;how_it_works?:string;who_uses_it?:string;when_used?:string;why_it_exists?:string;public_data_scope?:string;iris_capabilities?:string[];plaid_item_states?:string[];availability_notes?:string;pricing_notes?:string;official_source_url?:string;official_docs_url?:string};
const keys=["auth","transactions","balance","identity","assets","liabilities","investments","statements"];
const labels:Record<string,string>={observed:"Observed",active:"Active",consented:"Consented",available:"Available",not_available:"Not available",not_connected:"Not connected"};
const isActiveItem=(item: Item) => ["active","healthy","connected"].includes((item.status??"").toLowerCase());
export function PlaidCommandSurface(){
 const [runtime,setRuntime]=useState<any>(null),[knowledge,setKnowledge]=useState<Knowledge[]>([]),[mode,setMode]=useState("overview"),[query,setQuery]=useState(""),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const load=async()=>{setLoading(true);setError(null);try{const {data}=await supabase.auth.getSession();const token=data.session?.access_token??"";const [s,k]=await Promise.all([api.getPlaidSurface(),fetch(`${import.meta.env.VITE_BACKEND_URL}/dashboard/plaid/knowledge`,{headers:{Authorization:`Bearer ${token}`}})]);if(!k.ok)throw new Error("Plaid knowledge request failed");setRuntime(s);setKnowledge((await k.json()).records??[]);}catch(e){setError(e instanceof Error?e.message:"Unable to load Plaid source surface")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const items:Item[]=runtime?.items??[],products:Product[]=runtime?.products??[];
 const complete=items.filter(i=>keys.every(k=>i.products?.some(p=>p.key===k&&p.status==="observed"))).length;
 const activeItems=items.filter(isActiveItem).length;
 const filtered=useMemo(()=>knowledge.filter(k=>!query||JSON.stringify(k).toLowerCase().includes(query.toLowerCase())),[knowledge,query]);
 if(loading)return <main className="plaid-space"><div className="plaid-loader"><i/><b>PLAID / SOURCE CONTROL</b><span>Reading live provider state and evidence…</span></div></main>;
 if(error)return <main className="plaid-space"><div className="plaid-error"><b>PLAID / SOURCE CONTROL</b><h1>Surface unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry connection</button></div></main>;
 return <main className="plaid-space"><header className="plaid-command"><div className="plaid-brand"><span className="plaid-orbit"/><div><small>PLAID · SOURCE CONTROL</small><strong>PROVIDER COMMAND</strong></div></div><div className="plaid-command-right"><span className="live-dot">LIVE · READ ONLY</span><PlaidLinkButton onSuccess={()=>void load()}/></div></header>
  <section className="plaid-hero"><div><span className="eyebrow">CANONICAL 8-DOMAIN SURFACE</span><h1>Provider truth.<br/><em>Evidence before intelligence.</em></h1><p>Iris shows Plaid capability, consent and observation as different states. Iris may only use current provider evidence inside its evidence boundary.</p></div><div className="plaid-signal"><span>SAME-ITEM GATE</span><strong>{complete}/{items.length}</strong><small>Items with all eight observed</small></div></section>
  <nav className="plaid-tabs">{[["overview","Overview"],["items","Items"],["products","8 products"],["knowledge","Knowledge"]].map(([id,text])=><button key={id} className={mode===id?"active":""} onClick={()=>setMode(id)}>{text}</button>)}</nav>
  {mode==="overview"&&<><section className="plaid-grid plaid-overview"><Big label="Connected Items" value={items.length} note="Authenticated provider connections"/><Big label="Active Items" value={activeItems} note="Provider connection lifecycle"/><Big label="Observed domains" value={products.filter(p=>p.status==="observed").length} note="Current canonical evidence"/><Big label="Available domains" value={products.filter(p=>p.status==="available").length} note="Provider reports availability without current observation"/></section><section className="plaid-grid plaid-lower"><div className="plaid-panel wide"><Title eyebrow="LIVE PROVIDER STATE" title="Connected institutions" action="Open Items" onClick={()=>setMode("items")}/>{items.length?items.map(i=><ItemRow key={i.item_id} item={i}/>):<Empty text="No connected Items."/>}</div><div className="plaid-panel"><Title eyebrow="EVIDENCE COVERAGE" title="Canonical domains"/><div className="product-mini-grid">{products.map(p=><div key={p.key}><span>{p.displayName}</span><b className={`state ${p.status}`}>{labels[p.status]??p.status}</b></div>)}</div></section></section></>}
  {mode==="items"&&<section className="plaid-panel full"><Title eyebrow="LIVE RUNTIME / USER DATA" title="Provider Items" action="↻ Refresh" onClick={()=>void load()}/>{items.length?items.map(i=><ItemRow key={i.item_id} item={i} detailed refresh={()=>void load()}/>):<Empty text="No connected Items."/>}<Boundary/></section>}
  {mode==="products"&&<section className="plaid-panel full"><Title eyebrow="CANONICAL EVIDENCE CONTRACT" title="All eight Plaid domains"/><div className="product-table">{products.map(p=><article className="product-row" key={p.key}><div><strong>{p.displayName}</strong><span>{p.key}</span></div><b className={`state state-large ${p.status}`}>{labels[p.status]??p.status}</b><div><small>Items</small><b>{p.item_count??0}</b></div><div><small>Observed</small><b>{p.observed_item_count??0}</b></div><div><small>Active Items</small><b>{p.active_item_count??0}</b></div><div className="state-list">{items.map((i,n)=><span key={`${i.item_id}-${p.key}-${n}`} className={`state-dot ${i.products?.find(x=>x.key===p.key)?.status??"not_available"}`}>{i.institution_name??`Item ${n+1}`}: {labels[i.products?.find(x=>x.key===p.key)?.status??"not_available"]}</span>)}</div></article>)}</div><Boundary/></section>}
  {mode==="knowledge"&&<section className="plaid-panel full"><Title eyebrow="PUBLIC / OFFICIAL / READ-ONLY" title="Plaid knowledge"/><input className="plaid-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Plaid knowledge…"/><div className="knowledge-grid">{filtered.map(k=><article className={open===k.id?"knowledge-card open":"knowledge-card"} key={k.id}><button className="knowledge-head" onClick={()=>setOpen(open===k.id?null:k.id)}><span>{k.kind} · {k.category??"Plaid"}</span><b>{k.name}</b><small>{k.description}</small><i>{open===k.id?"−":"+"}</i></button>{open===k.id&&<div className="knowledge-detail"><Fact label="What" value={k.what_it_does}/><Fact label="How" value={k.how_it_works}/><Fact label="Who" value={k.who_uses_it}/><Fact label="When" value={k.when_used}/><Fact label="Why" value={k.why_it_exists}/><Fact label="Public scope" value={k.public_data_scope}/><Fact label="Iris mapping" value={(k.iris_capabilities??[]).join(", ")||"Reference only"}/><Fact label="Availability" value={k.availability_notes}/><Fact label="Commercial" value={k.pricing_notes}/><div className="source-links">{k.official_source_url&&<a href={k.official_source_url} target="_blank" rel="noreferrer">Official source ↗</a>}{k.official_docs_url&&<a href={k.official_docs_url} target="_blank" rel="noreferrer">Official docs ↗</a>}</div></div>}</article>)}</div></section>}
 </main>;
}
function Title({eyebrow,title,action,onClick}:{eyebrow:string;title:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{action&&<button onClick={onClick}>{action}</button>}</div>}
function Big({label,value,note}:{label:string;value:number;note:string}){return <div className="plaid-panel plaid-metric"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
function ItemRow({item,detailed,refresh}:{item:Item;detailed?:boolean;refresh?:()=>void}){const ps=item.products??[],obs=ps.filter(p=>p.status==="observed").length;return <div className={`runtime-row ${detailed?"detailed":""}`}><div className="institution-mark">{(item.institution_name??"P")[0].toUpperCase()}</div><div className="runtime-name"><b>{item.institution_name??"Institution"}</b><span>{item.status??"unknown"} · {item.last_synced_at?new Date(item.last_synced_at).toLocaleString():"sync not recorded"}</span></div><div className="runtime-state"><i/>{obs}/8 observed</div>{detailed&&<div className="runtime-products">{ps.map(p=><div className="runtime-product" key={p.key}><span>{p.displayName}</span><b className={`state ${p.status}`}>{labels[p.status]??p.status}</b></div>)}{refresh&&<PlaidEvidenceUpgradeButton itemId={item.item_id} observedProducts={ps.filter(p=>p.observed).map(p=>p.key)} onComplete={refresh}/>}</div>}</div>}
function Boundary(){return <div className="evidence-rail"><b>OBSERVATION BOUNDARY</b><span>Observed → Calculated → Pattern → Inference</span><small>Provider state is not silently promoted to financial evidence. Same-Item requirements remain intact.</small></div>}
function Empty({text}:{text:string}){return <div className="plaid-empty"><span>◌</span>{text}</div>}
function Fact({label,value}:{label:string;value?:string}){return <div className="fact"><span>{label}</span><p>{value||"—"}</p></div>}