import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import "./PlaidControlPlane.css";
import "./PlaidDeepSurface.css";

type AnyRecord = Record<string, any>;
const PRODUCTS = ["auth","transactions","balance","identity","assets","liabilities","investments","statements"];
const nameOf=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
function walk(v:any,path="root",out:string[]=[]):string[]{if(v===null||typeof v!=="object"){out.push(`${path} = ${v===null?"null":String(v)}`);return out}if(Array.isArray(v)){out.push(`${path} = Array(${v.length})`);v.forEach((x,i)=>walk(x,`${path}[${i}]`,out));return out}for(const[k,x]of Object.entries(v))walk(x,`${path}.${k}`,out);return out}
function rawSummary(r:AnyRecord){if(r.plaid_transaction_id)return `Transaction ${r.plaid_transaction_id}`;if(r.account_id)return `Account ${r.account_id}`;return `Observation ${r.id??"—"}`}
export function PlaidDeepSurface(){
 const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const[level,setLevel]=useState<"home"|"items"|"products"|"product"|"records"|"record"|"fields">("home");
 const[itemId,setItemId]=useState<string|null>(null),[product,setProduct]=useState<string|null>(null),[recordId,setRecordId]=useState<string|null>(null),[search,setSearch]=useState("");
 const load=async()=>{setLoading(true);setError(null);try{setData(await api.getPlaidSurface())}catch(e){setError(e instanceof Error?e.message:"Unable to load Plaid source data")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const evidence:AnyRecord[]=data?.provider_evidence??[],items:AnyRecord[]=data?.items??[],products=PRODUCTS.map(k=>data?.products?.find((p:any)=>p.key===k)).filter(Boolean) as AnyRecord[];
 const selectedItem=items.find(x=>x.item_id===itemId),selectedRecord=evidence.find(x=>String(x.id)===String(recordId));
 const records=useMemo(()=>evidence.filter(r=>(!itemId||r.item_id===itemId)&&(!product||String(r.product??r.source_domain)===product)),[evidence,itemId,product]);
 const filtered=useMemo(()=>records.filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase())),[records,search]);
 const go=(l:any,i:string|null=null,p:string|null=null,r:string|null=null)=>{setLevel(l);setItemId(i);setProduct(p);setRecordId(r);setSearch("");window.scrollTo({top:0,behavior:"smooth"})};
 if(loading)return <main className="plaid-space"><div className="plaid-loader"><b>PLAID / SOURCE CONTROL</b><span>Loading live provider evidence…</span></div></main>;
 if(error)return <main className="plaid-space"><div className="plaid-error"><b>PLAID / SOURCE CONTROL</b><h1>Surface unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></div></main>;
 const fieldRows=(product?data?.evidence_field_inventory?.[product]?.nested_field_inventory??[]:[]).filter((x:any)=>!search||x.path.toLowerCase().includes(search.toLowerCase()));
 return <main className="plaid-space">
  <header className="plaid-command"><div className="plaid-brand"><span className="plaid-orbit"/><div><small>PLAID · SOURCE CONTROL</small><strong>PROVIDER EVIDENCE EXPLORER</strong></div></div><div className="plaid-command-right"><span className="live-dot">LIVE · READ ONLY</span><button onClick={()=>void load()}>Refresh live data</button></div></header>
  <section className="plaid-hero"><div><span className="eyebrow">REAL PROVIDER DATA · NO MOCK DATA</span><h1>Every layer.<br/><em>Open the evidence.</em></h1><p>This surface exposes the actual evidence behind the Plaid connection. Counts are entry points—not decorations. Open them to reach Items, Products, Records, exact fields and raw responses.</p></div><div className="plaid-signal"><span>OBSERVED RECORDS</span><strong>{evidence.length}</strong><small>Current evidence exposed by the authenticated source boundary</small></div></section>
  <div className="plaid-deep-nav"><button onClick={()=>go("home")}>Plaid</button>{level!=="home"&&<><b>›</b><span>{itemId?`Item: ${selectedItem?.institution_name??itemId}`:product?nameOf(product):nameOf(level)}</span></>}{product&&<><b>›</b><span>{nameOf(product)}</span></>}{recordId&&<><b>›</b><span>Exact record</span></>}</div>
  {level==="home"&&<><section className="plaid-deep-grid"><button onClick={()=>go("items")}><span>CONNECTED ITEMS</span><strong>{items.length}</strong><small>Open every provider connection →</small></button><button onClick={()=>go("products")}><span>CANONICAL PRODUCTS</span><strong>8</strong><small>Open all eight domains →</small></button><button onClick={()=>go("records")}><span>OBSERVED RECORDS</span><strong>{evidence.length}</strong><small>Open exact provider observations →</small></button><button onClick={()=>go("fields",null,"transactions")}><span>RETURNED FIELDS</span><strong>{PRODUCTS.reduce((n,k)=>n+(data?.evidence_field_inventory?.[k]?.nested_field_inventory?.length??0),0)}</strong><small>Open field paths by product →</small></button></section><section className="plaid-panel full"><div className="panel-title"><div><span className="eyebrow">EIGHT CANONICAL DOMAINS</span><h2>Choose a product</h2></div></div><div className="plaid-deep-products">{products.map(p=><button key={p.key} onClick={()=>go("product",null,p.key)}><b>{p.displayName??nameOf(p.key)}</b><span className={`state ${p.status}`}>{p.status}</span><small>{p.observed_item_count??0} Items with observed evidence · {data?.provider_evidence_counts?.[p.key]??0} records</small><strong>Open domain →</strong></button>)}</div></section></>}
  {level==="items"&&<section className="plaid-panel full"><Title text="Connected Items" back={()=>go("home")}/><div className="plaid-deep-list">{items.map(i=><button key={i.item_id} onClick={()=>go("product",i.item_id,"transactions")}><span><b>{i.institution_name??"Provider Item"}</b><small>{i.item_id}</small></span><strong>Open Item →</strong></button>)}</section>}
  {level==="products"&&<section className="plaid-panel full"><Title text="Canonical Plaid Products" back={()=>go("home")}/><div className="plaid-deep-products">{products.map(p=><button key={p.key} onClick={()=>go("product",null,p.key)}><b>{p.displayName??nameOf(p.key)}</b><span className={`state ${p.status}`}>{p.status}</span><small>{data?.provider_evidence_counts?.[p.key]??0} current observed records</small><strong>Open product →</strong></button>)}</div></section>}
  {level==="product"&&<section className="plaid-panel full"><Title text={`${nameOf(product??"")} — Evidence`} back={()=>go("products")}/><div className="detail-meta"><Fact label="Product" value={product??"—"}/><Fact label="Records" value={String(records.length)}/><Fact label="Observed Items" value={String(data?.products?.find((p:any)=>p.key===product)?.observed_item_count??0)}/></div>{itemId&&<button className="drill-button" onClick={()=>go("records",itemId,product)}>Open all records for this Item →</button>}<h3>Provider records</h3>{records.length?<div className="plaid-deep-list">{records.slice(0,250).map((r,i)=><button key={String(r.id??i)} onClick={()=>go("record",r.item_id,product,String(r.id))}><span><b>{rawSummary(r)}</b><small>{r.acquired_at??r.fetched_at??r.observed_at??"Observation time unavailable"}</small></span><strong>Inspect exact record →</strong></button>)}</div>:<Empty text="No current observed provider records for this selection."/>}</section>}
  {(level==="records"||level==="fields")&&<section className="plaid-panel full"><Title text={level==="fields"?"Exact Returned Fields":"Observed Provider Records"} back={()=>go("home")}/><div className="plaid-deep-filters"><select value={product??""} onChange={e=>{setProduct(e.target.value||null);setLevel("records")}}><option value="">All products</option>{PRODUCTS.map(k=><option key={k} value={k}>{nameOf(k)}</option>)}</select><select value={itemId??""} onChange={e=>setItemId(e.target.value||null)}><option value="">All Items</option>{items.map(i=><option key={i.item_id} value={i.item_id}>{i.institution_name??i.item_id}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search exact provider fields or values…"/></div>{level==="fields"?(product?<div className="field-path-list">{fieldRows.map((f:any,i:number)=><code key={`${f.path}-${i}`}>{f.path} · records {f.records_present}/{f.record_count} · occurrences {f.occurrences} · null {f.null_records}</code>)}</div>:<Empty text="Choose a product to inspect its returned field paths."/>):<div className="plaid-deep-list">{filtered.slice(0,500).map((r,i)=><button key={String(r.id??i)} onClick={()=>go("record",r.item_id,String(r.product??r.source_domain),String(r.id))}><span><b>{nameOf(String(r.product??r.source_domain??"provider"))}</b><small>{rawSummary(r)} · Item {r.item_id??"—"}</small></span><strong>Inspect →</strong></button>)}</div>}</section>}
  {level==="record"&&selectedRecord&&<section className="plaid-panel full"><Title text="Exact Plaid Observation" back={()=>go(product?"product":"records",itemId,product)}/><div className="detail-meta">{Object.entries(selectedRecord).filter(([k])=>k!=="raw_response").map(([k,v])=><Fact key={k} label={nameOf(k)} value={typeof v==="object"?JSON.stringify(v):String(v??"null")}/>)}</div><div className="evidence-rail"><b>RAW SOURCE BOUNDARY</b><span>Observed provider evidence — no intelligence interpretation</span><small>Schema availability, returned data, null values and record-level absence remain distinct.</small></div><h3>Exact returned field paths</h3><div className="field-path-list">{walk(selectedRecord.raw_response).map((x,i)=><code key={i}>{x}</code>)}</div><details className="plaid-raw-details"><summary>Show exact raw Plaid response</summary><pre className="raw-view">{JSON.stringify(selectedRecord.raw_response,null,2)}</pre></details></section>}
 </main>;
}
function Title({text,back}:{text:string;back:()=>void}){return <div className="panel-title"><div><span className="eyebrow">PLAID / LIVE EVIDENCE</span><h2>{text}</h2></div><button onClick={back}>← Back</button></div>}
function Fact({label,value}:{label:string;value:string}){return <div className="fact"><span>{label}</span><p>{value||"—"}</p></div>}
function Empty({text}:{text:string}){return <div className="plaid-empty"><span>◌</span>{text}</div>}
