import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import "../styles/source-truth.css";

type SourceData = {
  source: string; read_only: boolean; provider: string; generated_at: string;
  counts: Record<string, number>; items: any[]; accounts: any[]; transactions: any[];
  observations: { transactions: any[]; balances: any[]; liabilities: any[] };
  product_observations: any[]; sync_runs: any[]; roundup_contributions: any[]; recurring_series: any[]; liabilities: any[]; calculation_audit: any[]; lineage: any[];
  evidence_legend: Record<string,string>;
};
const title=(s:string)=>s.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase());
const money=(n:any)=>typeof n!=="number"&&typeof n!=="string"?"—":`${Number(n)<0?"−":""}$${Math.abs(Number(n)).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const when=(v:any)=>v?v===String(v)?new Date(v).toLocaleString():new Date(v).toLocaleString():"—";

export function SourceTruth(){
  const [data,setData]=useState<SourceData|null>(null); const [page,setPage]=useState("overview"); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [question,setQuestion]=useState(""); const [answer,setAnswer]=useState<any>(null); const [asking,setAsking]=useState(false);
  const load=async()=>{setLoading(true);setError(null);try{setData(await api.getSourceTruth());}catch(e){setError(e instanceof Error?e.message:"Unable to load source data");}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const ask=async(q:string)=>{const text=q.trim();if(!text)return;setAsking(true);try{setAnswer(await api.askIris(text,{source_workspace:page}));}catch(e){setAnswer({answer:e instanceof Error?e.message:"Iris could not answer from current evidence"});}finally{setAsking(false);}};
  const nav=["overview","institutions","accounts","transactions","balances","income","investments","liabilities","recurring","evidence","sync","lineage","data quality"];
  if(loading)return <section className="source-page"><div className="source-loading">Loading your read-only source of truth…</div></section>;
  if(error)return <section className="source-page"><div className="source-error"><h1>Source data unavailable</h1><p>{error}</p><button onClick={()=>void load()}>Retry</button></div></section>;
  if(!data)return null;
  return <section className="source-page">
    <header className="source-hero"><div><span className="source-kicker">DATA SOURCE OF TRUTH · READ ONLY</span><h1>See what Iris actually knows.</h1><p>This workspace exposes the database-backed financial evidence Iris uses. It separates provider observations from canonical records and from Iris calculations. Nothing here gives you database write access.</p></div><div className="source-hero-actions"><button onClick={()=>void load()}>Refresh source</button><button onClick={()=>window.history.back()}>Back to Iris</button></div></header>
    <div className="source-boundary"><b>Source boundary</b><span>Plaid observations</span><i>→</i><span>canonical iBag records</span><i>→</i><span>evidence + lineage</span><i>→</i><span>Iris interpretation</span></div>
    <div className="source-layout"><aside className="source-nav"><strong>YOUR SOURCE</strong>{nav.map(n=><button key={n} className={page===n?"active":""} onClick={()=>setPage(n)}>{title(n)}</button>)}</aside><main className="source-main"><Summary data={data}/>{page==="overview"&&<Overview data={data} go={setPage}/>} {page==="institutions"&&<Institutions data={data}/>} {page==="accounts"&&<Accounts data={data}/>} {page==="transactions"&&<Transactions data={data} ask={ask}/>} {page==="balances"&&<Observations title="Balance observations" rows={data.observations.balances}/>} {page==="income"&&<DomainEmpty label="Income" data={data} question="What income evidence do you actually have?" ask={ask}/>} {page==="investments"&&<DomainEmpty label="Investments" data={data} question="What investment evidence do you actually have?" ask={ask}/>} {page==="liabilities"&&<Liabilities data={data}/>} {page==="recurring"&&<Recurring data={data}/>} {page==="evidence"&&<Evidence data={data}/>} {page==="sync"&&<Sync data={data}/>} {page==="lineage"&&<Lineage data={data}/>} {page==="data quality"&&<Quality data={data}/>}<AskBar question={question} setQuestion={setQuestion} ask={ask} asking={asking} answer={answer}/></main></div>
  </section>;
}
function Summary({data}:{data:SourceData}){return <div className="source-summary">{[["Institutions",data.counts.items],["Accounts",data.counts.accounts],["Transactions",data.counts.transactions],["Provider observations",data.counts.transaction_observations+data.counts.balance_observations+data.counts.liability_observations],["Product observations",data.counts.product_observations],["Sync runs",data.counts.sync_runs]].map(([l,v])=><div key={String(l)}><span>{l}</span><strong>{v}</strong></div>)}</div>}
function Overview({data,go}:{data:SourceData;go:(p:string)=>void}){return <><Panel title="What this means"><p><b>Observed</b> means the provider/source supplied the fact. <b>Calculated</b> means iBag derived it deterministically. <b>Inferred</b> means Iris interpreted a pattern. The source workspace never upgrades a weaker evidence state into a stronger one.</p></Panel><div className="source-cards">{[["Institutions","institutions",data.counts.items],["Accounts","accounts",data.counts.accounts],["Transactions","transactions",data.counts.transactions],["Evidence","evidence",data.counts.transaction_observations+data.counts.balance_observations+data.counts.liability_observations],["Sync & freshness","sync",data.counts.sync_runs],["Lineage","lineage",data.lineage.length]].map(([l,p,v])=><button key={String(p)} onClick={()=>go(String(p))}><span>{l}</span><strong>{v}</strong><small>Inspect source records →</small></button>)}</div><Panel title="Ask Iris"><p>Try: “What is the source of my current balance?” or “Show me what contributed to my spending calculation.” Iris receives the source-workspace context and is expected to explain the evidence rather than invent missing facts.</p></Panel></>}
function Institutions({data}:{data:SourceData}){return <Panel title="Connected institutions">{data.items.map((i:any)=><Record key={i.id}><div><b>{i.institution_name??"Institution"}</b><span>{title(i.status)}</span></div><small>Item {i.plaid_item_id} · Last synced {when(i.last_synced_at)}</small><small>Created {when(i.created_at)} · Updated {when(i.updated_at)}</small></Record>)}</Panel>}
function Accounts({data}:{data:SourceData}){return <Panel title="Canonical accounts">{data.accounts.map((a:any)=><Record key={a.id}><div><b>{a.name}</b><span>{money(a.current_balance??a.available_balance)}</span></div><small>{title(a.type??"account")} · {a.mask?`•••• ${a.mask}`:"mask unavailable"} · Item {a.item_id}</small><small>Balance observed {when(a.balance_updated_at)} · Round-Ups {a.roundup_enabled?"enabled":"disabled"}</small></Record>)}</Panel>}
function Transactions({data,ask}:{data:SourceData;ask:(q:string)=>void}){return <Panel title="Canonical transactions"><p className="source-note">Showing the most recent {data.transactions.length} canonical records in this read-only workspace. Each record links to its provider observation through <code>raw_transaction_id</code>.</p>{data.transactions.map((t:any)=><Record key={t.id}><div><b>{t.merchant_name??"Unknown merchant"}</b><span>{money(t.amount)}</span></div><small>{t.posted_date} · {t.iso_currency_code??"USD"} · {title(t.transaction_class)} · evidence: {title(t.classification_evidence)}</small><small>Canonical {t.id} · Provider transaction {t.plaid_transaction_id} · Raw observation {t.raw_transaction_id}</small><button className="source-ask" onClick={()=>ask(`Explain transaction ${t.plaid_transaction_id}: what was observed, how was it classified, and what can Iris responsibly infer from it?`)}>Ask Iris about this →</button></Record>)}</Panel>}
function Observations({title:heading,rows}:{title:string;rows:any[]}){return <Panel title={heading}>{rows.length?rows.map((r:any)=><Record key={r.id}><div><b>{r.provider_object_id??r.account_id??"Observation"}</b><span className={`evidence ${r.evidence_state}`}>{title(r.evidence_state)}</span></div><small>Observed {when(r.effective_at??r.fetched_at)} · acquired {when(r.acquired_at)}</small><small>Observation {r.id} · version {r.observation_version}</small><details><summary>View provider payload</summary><pre>{JSON.stringify(r.raw_response,null,2)}</pre></details></Record>):<Empty label="No observed records in this domain."/>}</Panel>}
function Liabilities({data}:{data:SourceData}){return <><Observations title="Provider liability observations" rows={data.observations.liabilities}/><Panel title="Canonical liability details">{data.liabilities.length?data.liabilities.map((l:any)=><Record key={l.id}><div><b>{title(l.liability_type)}</b><span>{money(l.last_statement_balance)}</span></div><small>APR {l.apr_percentage??"not observed"} · overdue {l.is_overdue==null?"not observed":String(l.is_overdue)}</small><small>Next payment {l.next_payment_due_date??"not observed"} · minimum {money(l.minimum_payment_amount)}</small></Record>):<Empty label="No canonical liability details currently observed."/>}</Panel></>}
function Recurring({data}:{data:SourceData}){return <Panel title="Recurring series">{data.recurring_series.length?data.recurring_series.map((r:any)=><Record key={r.id}><div><b>Merchant {r.merchant_id}</b><span>{money(r.typical_amount)}</span></div><small>Every {r.interval_days} days · occurrences {r.occurrence_count}</small><small>Last seen {r.last_seen_date??"—"} · next expected {r.next_expected_date??"—"} · essential {r.is_essential?"yes":"no"}</small></Record>):<Empty label="No recurring series currently observed."/>}</Panel>}
function Evidence({data}:{data:SourceData}){return <><Panel title="Evidence states">{Object.entries(data.evidence_legend).map(([k,v])=><Record key={k}><div><b className={`evidence ${k}`}>{title(k)}</b></div><small>{v}</small></Record>)}</Panel><Panel title="Product/domain observations">{data.product_observations.map((p:any)=><Record key={p.id}><div><b>{title(p.product)}</b><span className={`evidence ${p.evidence_state}`}>{title(p.evidence_state)}</span></div><small>{title(p.lifecycle_state)} · observed {when(p.observed_at)} · requested {p.requested?"yes":"no"}</small><small>Item {p.item_id} · provider object {p.provider_object_id??"not supplied"}</small></Record>)}</Panel></>}
function Sync({data}:{data:SourceData}){return <Panel title="Sync history & freshness">{data.sync_runs.map((s:any)=><Record key={s.id}><div><b>{title(s.state)}</b><span>{s.added_count??0} added · {s.modified_count??0} modified · {s.removed_count??0} removed</span></div><small>Requested {when(s.requested_at)} · completed {when(s.completed_at)}</small><small>Item {s.item_id} · pages {s.pages_processed??0} · error {s.error_message??"none"}</small></Record>)}</Panel>}
function Lineage({data}:{data:SourceData}){return <Panel title="Evidence lineage"><p>Lineage is the chain that lets Iris answer “where did this come from?” without treating an interpretation as a provider fact.</p>{data.lineage.slice(0,200).map((l:any)=><Record key={`${l.type}-${l.id}`}><div><b>{title(l.type)}</b><span className={`evidence ${l.evidence_state}`}>{title(l.evidence_state)}</span></div><small>Provider {l.provider} · object {l.object_id??"—"}</small><small>Source record {l.id} · canonical record {l.canonical_id??"not linked"} · observed {when(l.observed_at)}</small></Record>)}</Panel>}
function Quality({data}:{data:SourceData}){const broken=data.lineage.filter((l:any)=>!l.canonical_id).length;return <><Panel title="Data quality signals"><div className="quality-grid"><div><span>Provider observations</span><strong>{data.counts.transaction_observations+data.counts.balance_observations+data.counts.liability_observations}</strong></div><div><span>Lineage records</span><strong>{data.lineage.length}</strong></div><div><span>Unlinked observations in displayed lineage</span><strong>{broken}</strong></div><div><span>Read-only boundary</span><strong>Enforced</strong></div></div></Panel><Panel title="What Iris should do with uncertainty"><p>Missing or unlinked evidence is a limitation, not permission to guess. If a question depends on a domain that has not been observed, Iris should say what is missing, what was observed instead, and what would be needed for a stronger answer.</p></Panel></>}
function DomainEmpty({label,data,question,ask}:{label:string;data:SourceData;question:string;ask:(q:string)=>void}){return <Panel title={label}><Empty label={`No dedicated ${label.toLowerCase()} observation records are currently exposed by the source workspace.`}/><p className="source-note">This does not mean the information does not exist elsewhere; it means this canonical source contract does not currently expose an observed record for this domain. Iris should not manufacture one.</p><button className="source-ask" onClick={()=>ask(question)}>Ask Iris what evidence exists →</button></Panel>}
function AskBar({question,setQuestion,ask,asking,answer}:{question:string;setQuestion:(v:string)=>void;ask:(q:string)=>void;asking:boolean;answer:any}){return <section className="source-askbar"><span className="source-kicker">IRIS · EVIDENCE EXPLAINER</span><h2>Ask anything about this source.</h2><div><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void ask(question)}} placeholder="Where did this number come from? What is observed vs calculated?"/><button disabled={asking} onClick={()=>void ask(question)}>{asking?"Thinking…":"Ask Iris"}</button></div>{answer&&<article className="source-answer"><b>{answer.evidence_state?title(answer.evidence_state):"Iris response"}</b><p>{answer.answer}</p>{answer.limitations?.length?<ul>{answer.limitations.map((x:any,i:number)=><li key={i}>{typeof x==="string"?x:x.message??JSON.stringify(x)}</li>)}</ul>:null}</article>}</section>}
function Panel({title:heading,children}:{title:string;children:React.ReactNode}){return <section className="source-panel"><div className="source-panel-head"><h2>{heading}</h2></div>{children}</section>}
function Record({children}:{children:React.ReactNode}){return <article className="source-record">{children}</article>}
function Empty({label}:{label:string}){return <div className="source-empty">{label}</div>}
