import { createHash } from "node:crypto";
import { IRIS_ANALYSIS_ATLAS } from "./analysisAtlas.js";

const SOURCE_KEYS = new Set(["plaid_iris_field_map", "plaid_complete_field_architecture", "feature_flags"]);
const PROTECTED_KEYS = /(?:access.?token|refresh.?token|secret|api.?key|password|authorization|client.?secret)/i;

function stableId(parts: string[]) {
  return `iris-derived-field-${createHash("sha256").update(parts.join("|"), "utf8").digest("hex").slice(0, 24)}`;
}

function scalar(value: unknown) {
  return value === null || typeof value !== "object";
}

function familyForPath(path: string) {
  const root = path.split(".")[0];
  const match = IRIS_ANALYSIS_ATLAS.find((d) => d.inputs.includes(root));
  return match?.family ?? "synthesis";
}

function definitionForPath(path: string) {
  const root = path.split(".")[0];
  return IRIS_ANALYSIS_ATLAS.find((d) => d.inputs.includes(root)) ?? null;
}

function flattenDerived(value: unknown, path: string, out: any[], context: { userId: string; generatedAt: string; evidenceState: string }) {
  if (!scalar(value)) {
    if (Array.isArray(value)) value.forEach((child, index) => flattenDerived(child, `${path}[${index}]`, out, context));
    else Object.entries(value as Record<string, unknown>).forEach(([key, child]) => flattenDerived(child, path ? `${path}.${key}` : key, out, context));
    return;
  }
  const name = path.split(".").pop()?.replace(/\[\d+\]$/, "") ?? path;
  if (PROTECTED_KEYS.test(name)) return;
  const definition = definitionForPath(path);
  const family = familyForPath(path);
  out.push({
    field_id: stableId(["derived", context.userId, path, context.generatedAt]),
    field_name: name,
    path,
    value,
    value_type: value === null ? "null" : typeof value,
    source: "iris_intelligence",
    evidence_state: context.evidenceState,
    domain: family,
    subdomain: definition?.name ?? family,
    analysis_id: definition?.id ?? null,
    operation: "derive",
    generated_at: context.generatedAt,
    lineage: {
      input_source: "plaid_fields",
      analysis_definition: definition?.id ?? null,
      operation: "derive",
      evidence_state: context.evidenceState,
      source_path: path,
    },
  });
}

/**
 * Iris field universe = all applicable Plaid source fields + additive fields
 * generated by Iris domains/subdomains. Source fields are references, never
 * replacements. Derived fields carry domain/subdomain and operation lineage.
 */
export function buildIrisFieldArchitecture(userId: string, intelligence: Record<string, unknown>, plaidArchitecture: any) {
  const generatedAt = typeof intelligence.generated_at === "string" ? intelligence.generated_at : new Date().toISOString();
  const evidenceState = intelligence.intelligence_gate && (intelligence.intelligence_gate as any).higher_order_conclusions_enabled === false ? "limited" : "calculated";
  const derived: any[] = [];
  for (const [key, value] of Object.entries(intelligence)) {
    if (SOURCE_KEYS.has(key)) continue;
    if (key === "intelligence_gate" && value && typeof value === "object") continue;
    flattenDerived(value, key, derived, { userId, generatedAt, evidenceState });
  }

  const sourceFields = Array.isArray(plaidArchitecture?.fields) ? plaidArchitecture.fields.map((field: any) => ({
    ...field,
    source: "plaid",
    iris_role: "input_field",
    preserved_provider_field_name: field.exact_provider_field_name ?? field.field_name,
    derived: false,
  })) : [];

  const all = [...sourceFields, ...derived];
  const domains = [...new Set(derived.map((field) => field.domain))].sort();
  const subdomains = [...new Set(derived.map((field) => `${field.domain}:${field.subdomain}`))].sort();
  const operations = [...new Set(derived.map((field) => field.operation))].sort();

  return {
    architecture_version: "IRIS_COMPLETE_FIELD_ARCHITECTURE_V1",
    source_model: "Plaid fields are Iris input fields; Iris-derived fields are additive.",
    plaid_source_field_count: sourceFields.length,
    derived_field_count: derived.length,
    total_field_count: all.length,
    source_fields: sourceFields,
    derived_fields: derived,
    fields: all,
    domains,
    subdomains,
    operations,
    hierarchy: "Iris > domain > subdomain > analysis > operation > derived field, with Plaid source fields preserved as the input field universe",
    rules: [
      "Every applicable Plaid field remains available to Iris under its original provider field name/path.",
      "Iris intelligence adds fields; it does not overwrite provider fields with interpretations.",
      "Derived fields are created only from the intelligence payload actually computed for this user.",
      "Each derived field identifies its domain, subdomain/analysis, operation, and source-path lineage.",
      "Missing evidence remains missing/limited; it is never converted to a fabricated value.",
      "Products consume the field/intelligence universe; products are not architecture tiers."
    ]
  };
}
