import { getCanonicalTransactions, computeCanonicalSpendingHierarchy, computeEconomicCashFlow, computeCanonicalForwardProjection, isEconomicOutflow } from "./transactionSemantics.js";
import type { CapabilityExecutionContext, CapabilityOperatorResult, GovernedCapabilityResult } from "./capabilityOperators.js";

type Tx = Awaited<ReturnType<typeof getCanonicalTransactions>>[number];
const VERSION = "1.0.0";
const VERSION_BY_CAPABILITY: Record<string, string> = { learning: "1.1.0", emergent: "1.1.0" };
function evidence(txs: Tx[]): CapabilityOperatorResult["evidence_state"] { return txs.length ? "CALCULATED" : "INSUFFICIENT_EVIDENCE"; }
function wrap(capability_id: string, result: GovernedCapabilityResult, state: CapabilityOperatorResult["evidence_state"], c?: CapabilityExecutionContext): CapabilityOperatorResult { return { capability_id, operator_id: capability_id, operator_version: VERSION_BY_CAPABILITY[capability_id] ?? VERSION, evidence_state: state, result: { ...result, evidence: { state, source: "canonical_financial_transactions", transaction_count: result.transaction_count ?? null }, provenance: { source: "canonical_financial_transactions", provider_observations_created: false, financial_values_created: false, money_movement_executed: false, run_id: c?.runId ?? null, evidence_manifest_hash: c?.evidenceManifestHash ?? null, run_evidence_ids: [...(c?.runEvidenceIds ?? [])].sort(), evidence_boundary: c?.evidenceBoundary ?? c?.asOf ?? null, dependency_capabilities: Object.keys(c?.dependencyResults ?? {}).sort() } } }; }
function dep(c: CapabilityExecutionContext | undefined, id: string): CapabilityOperatorResult | null { return c?.dependencyResults?.[id] ?? null; }
function depResult(c: CapabilityExecutionContext | undefined, id: string): GovernedCapabilityResult | null { return dep(c, id)?.result ?? null; }
async function txs(userId: string, asOf?: string | null, evidenceBoundary?: string | null) { const anchor = asOf ? new Date(asOf) : new Date(); const boundary = evidenceBoundary ?? asOf ?? null; return getCanonicalTransactions(userId, new Date(anchor.getTime() - 365 * 86_400_000).toISOString().slice(0, 10), boundary); }
export async function executeAnalysis(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t);return wrap("analysis",{flow:computeEconomicCashFlow(t),spending:computeCanonicalSpendingHierarchy(t,30,c?.asOf),transaction_count:t.length,evidence_boundary:c?.evidenceBoundary??c?.asOf??null},s,c);}
export async function executeBehavioral(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),m=new Map<string,{label:string;count:number;amount:number}>(),k=new Map<string,{label:string;count:number;amount:number}>();for(const x of t.filter(isEconomicOutflow)){const mk=x.merchant_id??x.merchant_name??"unknown_merchant",mm=m.get(mk)??{label:x.merchant_name??"Unknown merchant",count:0,amount:0};mm.count++;mm.amount+=x.amount;m.set(mk,mm);const ck=x.subdomain?.key??"uncategorized",cc=k.get(ck)??{label:x.subdomain?.label??"Uncategorized",count:0,amount:0};cc.count++;cc.amount+=x.amount;k.set(ck,cc);}const total=[...m.values()].reduce((a,x)=>a+x.amount,0);return wrap("behavioral",{merchant_frequency:[...m.entries()].map(([key,v])=>({key,...v,share_pct:total?(v.amount/total)*100:null})).sort((a,b)=>b.amount-a.amount).slice(0,50),category_frequency:[...k.entries()].map(([key,v])=>({key,...v})).sort((a,b)=>b.amount-a.amount)},s,c);}
export async function executePattern(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),m=new Map<string,Tx[]>();for(const x of t.filter(isEconomicOutflow)){const key=x.merchant_id??x.merchant_name??x.id;(m.get(key)??(m.set(key,[]),m.get(key)!)).push(x);}const patterns=[...m.entries()].map(([key,r])=>{const a=r.map(x=>x.amount),mean=a.reduce((p,v)=>p+v,0)/a.length,d=r.slice(1).map((x,i)=>(new Date(x.posted_date).getTime()-new Date(r[i].posted_date).getTime())/86400000);const gap=d.length?d.reduce((p,v)=>p+v,0)/d.length:null;return{merchant_id:key,merchant_name:r[0].merchant_name??null,occurrences:r.length,mean_amount:mean,average_gap_days:gap};}).filter(x=>x.occurrences>=2).sort((a,b)=>b.occurrences-a.occurrences).slice(0,100);return wrap("pattern",{recurring_candidates:patterns,pattern_count:patterns.length},s,c);}
export async function executeRelationship(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),d=new Map<string,Map<string,number>>();for(const x of t.filter(isEconomicOutflow)){const key=x.domain?.key??"uncategorized",row=d.get(key)??new Map<string,number>();row.set(x.posted_date.slice(0,7),(row.get(x.posted_date.slice(0,7))??0)+x.amount);d.set(key,row);}const a=[...d.entries()];const rel:Record<string,unknown>[]=[];for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++){const common=[...a[i][1].keys()].filter(k=>a[j][1].has(k));if(common.length<3)continue;const av=common.map(k=>a[i][1].get(k)!),bv=common.map(k=>a[j][1].get(k)!);const am=av.reduce((p,v)=>p+v,0)/av.length,bm=bv.reduce((p,v)=>p+v,0)/bv.length,den=Math.sqrt(av.reduce((p,v)=>p+(v-am)**2,0)*bv.reduce((p,v)=>p+(v-bm)**2,0)),corr=den?av.reduce((p,v,n)=>p+(v-am)*(bv[n]-bm),0)/den:null;rel.push({left:a[i][0],right:a[j][0],common_months:common.length,correlation:corr,causal_claim:false});}return wrap("relationship",{relationships:rel},s,c);}
export async function executeAnomaly(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),g=new Map<string,number[]>(),out:Record<string,unknown>[]=[];for(const x of t.filter(isEconomicOutflow)){const key=x.subdomain?.key??"uncategorized";(g.get(key)??(g.set(key,[]),g.get(key)!)).push(x.amount);}for(const x of t.filter(isEconomicOutflow)){const v=g.get(x.subdomain?.key??"uncategorized")??[];if(v.length<5)continue;const q=[...v].sort((a,b)=>a-b),mid=Math.floor(q.length/2),med=q.length%2?q[mid]:(q[mid-1]+q[mid])/2,dev=q.map(z=>Math.abs(z-med)).sort((a,b)=>a-b),dm=Math.floor(dev.length/2),mad=dev.length%2?dev[dm]:(dev[dm-1]+dev[dm])/2,z=mad?0.67448975*(x.amount-med)/mad:null;if(z!==null&&Math.abs(z)>=3.5)out.push({transaction_id:x.id,merchant_name:x.merchant_name,amount:x.amount,category:x.subdomain?.label??"Uncategorized",median:med,mad,robust_z:z,method:"median_mad"});}return wrap("anomaly",{detections:out,detection_count:out.length},s,c);}
export async function executeCausal(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t);if(t.length<30)return wrap("causal",{candidate_explanations:[],causal_claims:false,limitation:"At least 30 canonical transactions are required."},s,c);const f=computeEconomicCashFlow(t),h=computeCanonicalSpendingHierarchy(t,30,c?.asOf);return wrap("causal",{candidate_explanations:h.slice(0,10).map(x=>({domain:x.label,amount:x.amount,material:x.amount>f.outflow*.2,causal_claim:false})),method:"observational_candidate_analysis",causal_claims:false},s,c);}
export async function executePredictive(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t);if(!t.length)return wrap("predictive",{projection:null,limitation:"Certified transaction evidence is unavailable."},s,c);return wrap("predictive",{projection:await computeCanonicalForwardProjection(userId,30,c?.asOf),historical_daily_net_rate:computeEconomicCashFlow(t).net/365,forecast_type:"constrained_forward_projection"},s,c);}
export async function executeScenario(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),o=computeEconomicCashFlow(t).outflow,p=depResult(c,"predictive");if(!t.length)return wrap("scenario",{scenarios:[],dependency_evidence:{predictive:p!==null}},s,c);const projection=p?.projection??null;return wrap("scenario",{baseline_annualized_outflow:o,scenarios:[.05,.1,.2,.3].map(r=>({reduction_pct:r*100,annualized_outflow_reduction:o*r,projected_context:projection,assumption:"Uniform reduction of observed economic outflow; behavior is not asserted."})),composition:{uses_predictive_output:p!==null,predictive_evidence_state:dep(c,"predictive")?.evidence_state??null}},s,c);}
export async function executeDecision(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t),o=computeEconomicCashFlow(t).outflow,h=computeCanonicalSpendingHierarchy(t,30,c?.asOf);if(!t.length)return wrap("decision",{options:[]},s,c);const scenario=depResult(c,"scenario"),risk=depResult(c,"anomaly"),relationship=depResult(c,"relationship");return wrap("decision",{options:h.slice(0,5).map((x,i)=>({rank:i+1,domain:x.label,current_amount:x.amount,decision_lever:"review",reason:x.amount>o*.15?"Material observed outflow component":"Observed outflow component",money_movement:false})),dependency_context:{scenario_available:scenario!==null,risk_signal_available:risk!==null,relationship_signal_available:relationship!==null},decision_basis:{scenario,anomaly:risk,relationship}},s,c);}
export async function executeRecommendation(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t);if(!t.length)return wrap("recommendation",{recommendations:[]},s,c);const decision=depResult(c,"decision"),anomaly=depResult(c,"anomaly"),behavioral=depResult(c,"behavioral");return wrap("recommendation",{recommendations:computeCanonicalSpendingHierarchy(t,30,c?.asOf).slice(0,5).map(x=>({type:"review",subject:x.label,observed_amount:x.amount,why:"Observed spending category worth user review",money_movement:false})),dependency_context:{decision_available:decision!==null,anomaly_available:anomaly!==null,behavioral_available:behavioral!==null},decision_context:decision,signal_context:{anomaly,behavioral}},s,c);}
export async function executeOutcome(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary);return wrap("outcome",{outcomes:[],outcome_state:"INSUFFICIENT_EVIDENCE",limitation:"A later observed outcome is required; no outcome is inferred from activity alone.",dependency_context:Object.keys(c?.dependencyResults??{}).sort()},evidence(t),c);}
export async function executeLearning(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary);const outcomes=depResult(c,"outcome");return wrap("learning",{learned_patterns:[],learning_state:"INSUFFICIENT_EVIDENCE",limitation:"Validated outcomes across time are required for learning.",outcome_evidence_available:outcomes!==null},evidence(t),c);}
export async function executeEmergent(userId:string,c?:CapabilityExecutionContext):Promise<CapabilityOperatorResult>{const t=await txs(userId,c?.asOf,c?.evidenceBoundary),s=evidence(t);if(!t.length)return wrap("emergent",{discoveries:[],composition_depth:0},s,c);const f=computeEconomicCashFlow(t),h=computeCanonicalSpendingHierarchy(t,30,c?.asOf),dependencies=Object.entries(c?.dependencyResults??{}).map(([capability_id,value])=>({capability_id,evidence_state:value.evidence_state,output_hash:null}));return wrap("emergent",{discoveries:h.slice(0,5).map(x=>({type:"cross_domain_signal",domain:x.label,amount:x.amount,share_pct:f.outflow?(x.amount/f.outflow)*100:null,causal_claim:false})),composition_depth:Math.max(1,dependencies.length+1),composed_capabilities:dependencies,composed_inputs:Object.fromEntries(Object.entries(c?.dependencyResults??{}).map(([id,value])=>[id,{evidence_state:value.evidence_state,result:value.result}]))},s,c);}
