import { PLAID_PRODUCT_CATALOG as BASE_CATALOG, type PlaidProductDefinition } from "./plaidProductCatalog.js";

const ADDITIONAL_PRODUCTS: readonly PlaidProductDefinition[] = [
  {
    key: "identity_match",
    displayName: "Identity Match",
    category: "payments",
    description: "Generate an identity match score against institution-held account-owner information.",
    phase1Relevant: false,
    irisCapabilities: ["account_identity", "ownership_evidence", "risk"],
    plaidProductStates: ["identity_match"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "payment_initiation",
    displayName: "Payment Initiation",
    category: "payments",
    description: "Initiate supported bank payments through Plaid payment rails.",
    phase1Relevant: false,
    irisCapabilities: ["money_movement"],
    plaidProductStates: ["payment_initiation"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "virtual_accounts",
    displayName: "Virtual Accounts",
    category: "payments",
    description: "Provide virtual-account payment and balance capabilities where supported.",
    phase1Relevant: false,
    irisCapabilities: ["account_linkage", "cash_flow", "money_movement"],
    plaidProductStates: ["virtual_accounts"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "payouts",
    displayName: "Payouts",
    category: "payments",
    description: "Support eligible payout flows through Plaid payment infrastructure.",
    phase1Relevant: false,
    irisCapabilities: ["money_movement"],
    plaidProductStates: ["payouts"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "variable_recurring_payments",
    displayName: "Variable Recurring Payments",
    category: "payments",
    description: "Support eligible recurring bank-payment authorization flows.",
    phase1Relevant: false,
    irisCapabilities: ["recurring_payments", "money_movement"],
    plaidProductStates: ["variable_recurring_payments"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "consumer_report",
    displayName: "Consumer Report by Plaid Check",
    category: "lending",
    description: "Provide permissioned financial, income, cash-flow and risk reports through Plaid Check.",
    phase1Relevant: true,
    irisCapabilities: ["financial_state", "income", "cash_flow", "stability", "risk", "forecasting", "credit"],
    plaidProductStates: ["cra_base_report", "cra_income_insights", "cra_cashflow_insights", "cra_network_insights", "cra_partner_insights", "cra_monitoring", "cra_lend_score", "cra_home_lending"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "cash_flow_insights",
    displayName: "Cash Flow Insights",
    category: "lending",
    description: "Plaid Check cash-flow insights derived from permissioned financial data.",
    phase1Relevant: true,
    irisCapabilities: ["cash_flow", "stability", "risk", "forecasting"],
    plaidProductStates: ["cra_cashflow_insights"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "income_insights",
    displayName: "Income Insights",
    category: "lending",
    description: "Plaid Check income insights including income history and predictive attributes.",
    phase1Relevant: true,
    irisCapabilities: ["income", "stability", "timing", "forecasting"],
    plaidProductStates: ["cra_income_insights"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "network_insights",
    displayName: "Network Insights",
    category: "lending",
    description: "Plaid Check connection-history and network-derived insights where permitted.",
    phase1Relevant: false,
    irisCapabilities: ["risk", "data_relationships"],
    plaidProductStates: ["cra_network_insights"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "partner_insights",
    displayName: "Partner Insights",
    category: "lending",
    description: "Plaid Check partner-derived insights available for supported use cases.",
    phase1Relevant: false,
    irisCapabilities: ["cash_flow", "risk"],
    plaidProductStates: ["cra_partner_insights"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "plaid_check_lend_score",
    displayName: "Plaid Check LendScore",
    category: "lending",
    description: "Plaid Check LendScore risk signal.",
    phase1Relevant: false,
    irisCapabilities: ["credit_risk", "risk"],
    plaidProductStates: ["cra_lend_score"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "employment",
    displayName: "Employment",
    category: "lending",
    description: "Supported employment-related financial verification data.",
    phase1Relevant: false,
    irisCapabilities: ["income", "stability", "employment"],
    plaidProductStates: ["employment"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "standing_orders",
    displayName: "Standing Orders",
    category: "payments",
    description: "Supported recurring bank-order information.",
    phase1Relevant: true,
    irisCapabilities: ["recurring", "bills", "cash_flow", "forecasting"],
    plaidProductStates: ["standing_orders"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "transactions_refresh",
    displayName: "Transactions Refresh",
    category: "financial_management",
    description: "Refresh transaction data for supported Items.",
    phase1Relevant: true,
    irisCapabilities: ["freshness", "spending", "cash_flow"],
    plaidProductStates: ["transactions_refresh"],
    pricing: "included_unless_plaid_charges",
  },
  {
    key: "recurring_transactions",
    displayName: "Recurring Transactions",
    category: "financial_management",
    description: "Identify recurring transaction streams.",
    phase1Relevant: true,
    irisCapabilities: ["recurring", "bills", "cash_flow", "forecasting"],
    plaidProductStates: ["recurring_transactions"],
    pricing: "included_unless_plaid_charges",
  },
] as const;

export const PLAID_PRODUCT_CATALOG_V2: readonly PlaidProductDefinition[] = [
  ...BASE_CATALOG,
  ...ADDITIONAL_PRODUCTS,
];
