-- Fresh-built category hierarchy, generated from Plaid's real
-- Personal Finance Category taxonomy (fetched from
-- https://plaid.com/documents/transactions-personal-finance-category-taxonomy.csv).
-- No fabricated categories: every detailed code below is a real Plaid PFC value.

insert into public.domains (key, label, sort_order) values
  ('income', 'Income', 1),
  ('transfers', 'Transfers', 2),
  ('debt_and_fees', 'Debt & Fees', 3),
  ('housing', 'Housing & Home', 4),
  ('daily_living', 'Daily Living', 5),
  ('transportation_travel', 'Transportation & Travel', 6),
  ('entertainment', 'Entertainment & Leisure', 7),
  ('services_civic', 'Services, Government & Giving', 8)
on conflict (key) do nothing;

insert into public.subdomains (domain_id, key, label, sort_order) values
  ((select id from public.domains where key = 'income'), 'earned', 'Earned Income', 1),
  ((select id from public.domains where key = 'income'), 'investment_income', 'Investment & Retirement Income', 2),
  ((select id from public.domains where key = 'income'), 'benefits_refunds', 'Benefits & Refunds', 3),
  ((select id from public.domains where key = 'income'), 'other_income', 'Other Income', 4),
  ((select id from public.domains where key = 'transfers'), 'savings_investing_transfers', 'Savings & Investing Transfers', 1),
  ((select id from public.domains where key = 'transfers'), 'account_transfers', 'Account Transfers', 2),
  ((select id from public.domains where key = 'transfers'), 'cash_loans_transfers', 'Cash, Loans & Withdrawals', 3),
  ((select id from public.domains where key = 'debt_and_fees'), 'loan_payments', 'Loan Payments', 1),
  ((select id from public.domains where key = 'debt_and_fees'), 'bank_fees', 'Bank & Card Fees', 2),
  ((select id from public.domains where key = 'housing'), 'rent_utilities', 'Rent & Utilities', 1),
  ((select id from public.domains where key = 'housing'), 'home_improvement', 'Home Improvement', 2),
  ((select id from public.domains where key = 'daily_living'), 'food_drink', 'Food & Drink', 1),
  ((select id from public.domains where key = 'daily_living'), 'shopping', 'Shopping & Merchandise', 2),
  ((select id from public.domains where key = 'daily_living'), 'personal_care', 'Personal Care', 3),
  ((select id from public.domains where key = 'daily_living'), 'health', 'Health & Medical', 4),
  ((select id from public.domains where key = 'transportation_travel'), 'everyday_transport', 'Everyday Transportation', 1),
  ((select id from public.domains where key = 'transportation_travel'), 'travel', 'Travel', 2),
  ((select id from public.domains where key = 'entertainment'), 'entertainment_leisure', 'Entertainment & Leisure', 1),
  ((select id from public.domains where key = 'services_civic'), 'professional_services', 'Professional & Personal Services', 1),
  ((select id from public.domains where key = 'services_civic'), 'government_giving', 'Government, Taxes & Giving', 2)
on conflict (domain_id, key) do nothing;

insert into public.category_mapping (subdomain_id, plaid_category_detailed) values
  ((select id from public.subdomains where key = 'investment_income'), 'INCOME_DIVIDENDS'),
  ((select id from public.subdomains where key = 'investment_income'), 'INCOME_INTEREST_EARNED'),
  ((select id from public.subdomains where key = 'investment_income'), 'INCOME_RETIREMENT_PENSION'),
  ((select id from public.subdomains where key = 'benefits_refunds'), 'INCOME_TAX_REFUND'),
  ((select id from public.subdomains where key = 'benefits_refunds'), 'INCOME_UNEMPLOYMENT'),
  ((select id from public.subdomains where key = 'earned'), 'INCOME_WAGES'),
  ((select id from public.subdomains where key = 'other_income'), 'INCOME_OTHER_INCOME'),
  ((select id from public.subdomains where key = 'cash_loans_transfers'), 'TRANSFER_IN_CASH_ADVANCES_AND_LOANS'),
  ((select id from public.subdomains where key = 'cash_loans_transfers'), 'TRANSFER_IN_DEPOSIT'),
  ((select id from public.subdomains where key = 'savings_investing_transfers'), 'TRANSFER_IN_INVESTMENT_AND_RETIREMENT_FUNDS'),
  ((select id from public.subdomains where key = 'savings_investing_transfers'), 'TRANSFER_IN_SAVINGS'),
  ((select id from public.subdomains where key = 'account_transfers'), 'TRANSFER_IN_ACCOUNT_TRANSFER'),
  ((select id from public.subdomains where key = 'account_transfers'), 'TRANSFER_IN_OTHER_TRANSFER_IN'),
  ((select id from public.subdomains where key = 'savings_investing_transfers'), 'TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS'),
  ((select id from public.subdomains where key = 'savings_investing_transfers'), 'TRANSFER_OUT_SAVINGS'),
  ((select id from public.subdomains where key = 'cash_loans_transfers'), 'TRANSFER_OUT_WITHDRAWAL'),
  ((select id from public.subdomains where key = 'account_transfers'), 'TRANSFER_OUT_ACCOUNT_TRANSFER'),
  ((select id from public.subdomains where key = 'account_transfers'), 'TRANSFER_OUT_OTHER_TRANSFER_OUT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_CAR_PAYMENT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_CREDIT_CARD_PAYMENT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_PERSONAL_LOAN_PAYMENT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_MORTGAGE_PAYMENT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT'),
  ((select id from public.subdomains where key = 'loan_payments'), 'LOAN_PAYMENTS_OTHER_PAYMENT'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_ATM_FEES'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_FOREIGN_TRANSACTION_FEES'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_INSUFFICIENT_FUNDS'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_INTEREST_CHARGE'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_OVERDRAFT_FEES'),
  ((select id from public.subdomains where key = 'bank_fees'), 'BANK_FEES_OTHER_BANK_FEES'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_CASINOS_AND_GAMBLING'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_MUSIC_AND_AUDIO'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_TV_AND_MOVIES'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_VIDEO_GAMES'),
  ((select id from public.subdomains where key = 'entertainment_leisure'), 'ENTERTAINMENT_OTHER_ENTERTAINMENT'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_COFFEE'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_FAST_FOOD'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_GROCERIES'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_RESTAURANT'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_VENDING_MACHINES'),
  ((select id from public.subdomains where key = 'food_drink'), 'FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_CONVENIENCE_STORES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_DEPARTMENT_STORES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_DISCOUNT_STORES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_ELECTRONICS'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_OFFICE_SUPPLIES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_ONLINE_MARKETPLACES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_PET_SUPPLIES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_SPORTING_GOODS'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_SUPERSTORES'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_TOBACCO_AND_VAPE'),
  ((select id from public.subdomains where key = 'shopping'), 'GENERAL_MERCHANDISE_OTHER_GENERAL_MERCHANDISE'),
  ((select id from public.subdomains where key = 'home_improvement'), 'HOME_IMPROVEMENT_FURNITURE'),
  ((select id from public.subdomains where key = 'home_improvement'), 'HOME_IMPROVEMENT_HARDWARE'),
  ((select id from public.subdomains where key = 'home_improvement'), 'HOME_IMPROVEMENT_REPAIR_AND_MAINTENANCE'),
  ((select id from public.subdomains where key = 'home_improvement'), 'HOME_IMPROVEMENT_SECURITY'),
  ((select id from public.subdomains where key = 'home_improvement'), 'HOME_IMPROVEMENT_OTHER_HOME_IMPROVEMENT'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_DENTAL_CARE'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_EYE_CARE'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_NURSING_CARE'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_PHARMACIES_AND_SUPPLEMENTS'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_PRIMARY_CARE'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_VETERINARY_SERVICES'),
  ((select id from public.subdomains where key = 'health'), 'MEDICAL_OTHER_MEDICAL'),
  ((select id from public.subdomains where key = 'personal_care'), 'PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS'),
  ((select id from public.subdomains where key = 'personal_care'), 'PERSONAL_CARE_HAIR_AND_BEAUTY'),
  ((select id from public.subdomains where key = 'personal_care'), 'PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING'),
  ((select id from public.subdomains where key = 'personal_care'), 'PERSONAL_CARE_OTHER_PERSONAL_CARE'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_AUTOMOTIVE'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_CHILDCARE'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_CONSULTING_AND_LEGAL'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_EDUCATION'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_INSURANCE'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_POSTAGE_AND_SHIPPING'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_STORAGE'),
  ((select id from public.subdomains where key = 'professional_services'), 'GENERAL_SERVICES_OTHER_GENERAL_SERVICES'),
  ((select id from public.subdomains where key = 'government_giving'), 'GOVERNMENT_AND_NON_PROFIT_DONATIONS'),
  ((select id from public.subdomains where key = 'government_giving'), 'GOVERNMENT_AND_NON_PROFIT_GOVERNMENT_DEPARTMENTS_AND_AGENCIES'),
  ((select id from public.subdomains where key = 'government_giving'), 'GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT'),
  ((select id from public.subdomains where key = 'government_giving'), 'GOVERNMENT_AND_NON_PROFIT_OTHER_GOVERNMENT_AND_NON_PROFIT'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_BIKES_AND_SCOOTERS'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_GAS'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_PARKING'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_PUBLIC_TRANSIT'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_TAXIS_AND_RIDE_SHARES'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_TOLLS'),
  ((select id from public.subdomains where key = 'everyday_transport'), 'TRANSPORTATION_OTHER_TRANSPORTATION'),
  ((select id from public.subdomains where key = 'travel'), 'TRAVEL_FLIGHTS'),
  ((select id from public.subdomains where key = 'travel'), 'TRAVEL_LODGING'),
  ((select id from public.subdomains where key = 'travel'), 'TRAVEL_RENTAL_CARS'),
  ((select id from public.subdomains where key = 'travel'), 'TRAVEL_OTHER_TRAVEL'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_GAS_AND_ELECTRICITY'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_INTERNET_AND_CABLE'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_RENT'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_SEWAGE_AND_WASTE_MANAGEMENT'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_TELEPHONE'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_WATER'),
  ((select id from public.subdomains where key = 'rent_utilities'), 'RENT_AND_UTILITIES_OTHER_UTILITIES')
on conflict (plaid_category_detailed) do nothing;
