-- Rebuild the runtime capability registry from the executable Iris operator set.
-- This migration creates no user or financial data. Every row describes a governed
-- executable capability and its evidence/dependency contract.
insert into public.iris_capability_contracts (
  capability_id, version, operator_id, operator_version,
  evidence_requirements, dependencies, validation_rules, output_type,
  recursive, cross_domain, active, output_contract, lineage_requirements,
  resource_limits, user_control
) values
('temporal','1.0.0','temporal','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'[]'::jsonb,'["evidence_bounded","no_future_leakage","lineage_present"]'::jsonb,'temporal',true,true,true,'{"type":"temporal","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000,"max_graph_nodes":10000,"max_graph_edges":30000,"max_compositions":5000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('financial_life_state','1.0.0','financial_life_state','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'[]'::jsonb,'["evidence_bounded","observed_output_forbidden","lineage_present"]'::jsonb,'financial_life_state',true,true,true,'{"type":"financial_life_state","evidence_state_policy":["CALCULATED","INSUFFICIENT_EVIDENCE"],"observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('relational_ontology','1.0.0','relational_ontology','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["financial_life_state"]'::jsonb,'["evidence_bounded","relationships_not_causation","lineage_present"]'::jsonb,'relational_ontology',true,true,true,'{"type":"relational_ontology","evidence_state_policy":["CALCULATED","INSUFFICIENT_EVIDENCE"],"observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('analysis','1.0.0','analysis','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["temporal"]'::jsonb,'["evidence_bounded","lineage_present"]'::jsonb,'analysis',true,false,true,'{"type":"analysis","evidence_state_policy":["CALCULATED","INSUFFICIENT_EVIDENCE"],"observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('behavioral','1.0.0','behavioral','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis"]'::jsonb,'["descriptive_unless_supported","evidence_bounded","lineage_present"]'::jsonb,'behavioral',true,false,true,'{"type":"behavioral","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('pattern','1.0.0','pattern','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis","behavioral"]'::jsonb,'["evidence_bounded","no_unsupported_recurrence_claim","lineage_present"]'::jsonb,'pattern',true,false,true,'{"type":"pattern","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('relationship','1.0.0','relationship','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["pattern","relational_ontology"]'::jsonb,'["association_not_causation","evidence_bounded","lineage_present"]'::jsonb,'relationship',true,true,true,'{"type":"relationship","causal_claim_forbidden_without_supported_evidence":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('anomaly','1.0.0','anomaly','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis","temporal","behavioral","pattern"]'::jsonb,'["evidence_bounded","anomaly_not_fraud","lineage_present"]'::jsonb,'anomaly',true,true,true,'{"type":"anomaly","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('causal','1.0.0','causal','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["relationship"]'::jsonb,'["causal_claim_requires_supported_evidence","correlation_not_causation","lineage_present"]'::jsonb,'causal',true,true,true,'{"type":"causal","unsupported_causal_claim_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('predictive','1.0.0','predictive','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["causal","temporal"]'::jsonb,'["history_only","future_leakage_forbidden","uncertainty_required","lineage_present"]'::jsonb,'predictive',true,true,true,'{"type":"predictive","observed_output_forbidden":true,"assumptions_required":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('risk','1.0.0','risk','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis","behavioral","anomaly","predictive"]'::jsonb,'["evidence_bounded","probability_not_invented","lineage_present"]'::jsonb,'risk',true,true,true,'{"type":"risk","observed_output_forbidden":true,"probability_claims_require_model":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000,"max_graph_nodes":10000,"max_graph_edges":30000,"max_compositions":5000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('scenario','1.0.0','scenario','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["predictive","risk"]'::jsonb,'["explicit_assumptions_required","hypothetical_state_distinct_from_observation","lineage_present"]'::jsonb,'scenario',true,true,true,'{"type":"scenario","assumptions_required":true,"observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('decision','1.0.0','decision','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["scenario","risk"]'::jsonb,'["evidence_bounded","no_action_execution","lineage_present"]'::jsonb,'decision',true,true,true,'{"type":"decision","action_execution_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('recommendation','1.0.0','recommendation','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["decision"]'::jsonb,'["evidence_bounded","no_action_execution","lineage_present"]'::jsonb,'recommendation',true,true,true,'{"type":"recommendation","action_execution_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('opportunity','1.0.0','opportunity','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis","behavioral","scenario","recommendation"]'::jsonb,'["evidence_bounded","no_guaranteed_benefit","lineage_present"]'::jsonb,'opportunity',true,true,true,'{"type":"opportunity","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000,"max_graph_nodes":10000,"max_graph_edges":30000,"max_compositions":5000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('consequence','1.0.0','consequence','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["risk","opportunity","scenario","decision"]'::jsonb,'["conditional_only","hypothetical_state_distinct_from_observation","lineage_present"]'::jsonb,'consequence',true,true,true,'{"type":"consequence","observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000,"max_graph_nodes":10000,"max_graph_edges":30000,"max_compositions":5000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('outcome','1.0.0','outcome','1.0.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["decision","recommendation"]'::jsonb,'["observed_outcome_required","no_outcome_inference","lineage_present"]'::jsonb,'outcome',true,true,true,'{"type":"outcome","observed_outcome_required":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('learning','1.1.0','learning','1.1.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["outcome"]'::jsonb,'["validated_outcome_required","no_learning_from_unobserved_outcomes","lineage_present"]'::jsonb,'learning',true,true,true,'{"type":"learning","validated_outcome_required":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb),
('emergent','1.1.0','emergent','1.1.0','["canonical_transactions","run_evidence","source_lineage"]'::jsonb,'["analysis","behavioral","pattern","relationship","causal","predictive","risk","scenario","decision","recommendation","opportunity","consequence","outcome","learning","financial_life_state","relational_ontology"]'::jsonb,'["evidence_bounded","dependency_lineage_required","no_unobserved_evidence_promotion","lineage_present"]'::jsonb,'emergent',true,true,true,'{"type":"emergent","evidence_state_policy":["INFERRED","INSUFFICIENT_EVIDENCE"],"observed_output_forbidden":true}'::jsonb,'["run_evidence","source_lineage"]'::jsonb,'{"max_execution_time_ms":120000,"max_graph_nodes":10000,"max_graph_edges":30000,"max_compositions":5000}'::jsonb,'{"user_controllable":true,"enabled_by_default":true}'::jsonb)
on conflict (capability_id,version) do update set
  operator_id=excluded.operator_id,
  operator_version=excluded.operator_version,
  evidence_requirements=excluded.evidence_requirements,
  dependencies=excluded.dependencies,
  validation_rules=excluded.validation_rules,
  output_type=excluded.output_type,
  recursive=excluded.recursive,
  cross_domain=excluded.cross_domain,
  active=excluded.active,
  output_contract=excluded.output_contract,
  lineage_requirements=excluded.lineage_requirements,
  resource_limits=excluded.resource_limits,
  user_control=excluded.user_control;
